#fire gem powers







every 1 tick:
	loop all players:
		set {_uuid} to uuid of loop-player
		
		if loop-player's off hand item or loop-player's held item is a amethyst shard named "&6&lFire &lgem":
			send action bar "&6🔺%{Fire.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player



		if loop-player's off hand item is prismarine shard named "&6&lFire &lgem":

			send action bar "%{Fire.Power1.Fireball.Display.%{_uuid}%}% &6🔮%{Fire.Power2.Enchanting.Display.%{_uuid}%}% %{Fire.Power3.Campfire.Display.%{_uuid}%}%" to loop-player
		
		
		if loop-player's held item or loop-player's held item is a amethyst shard named "&6&lFire &lgem":
			send action bar "&6🔺%{Fire.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player



		if loop-player's held item is prismarine shard named "&6&lFire &lgem":

			send action bar "%{Fire.Power1.Fireball.Display.%{_uuid}%}% &6🔮%{Fire.Power2.Enchanting.Display.%{_uuid}%}% %{Fire.Power3.Campfire.Display.%{_uuid}%}%" to loop-player



every 1 second:
	loop all players:
		set {_uuid} to uuid of loop-player
		if loop-player has a prismarine shard or amethyst shard named "&6&lFire &lgem":


			#Campfire
			
			if {Fire.Power3.Campfire.Second.%{_uuid}%} is not set:
				set {Fire.Power3.Campfire.Second.%{_uuid}%} to 0
				set {Fire.Power3.Campfire.Minute.%{_uuid}%} to 0
				set {Fire.Power3.Campfire.Cooldown.%{_uuid}%} to true
		
			if {Fire.Power3.Campfire.Cooldown.%{_uuid}%} is true:
				if {Fire.Power3.Campfire.Minute.%{_uuid}%} is 0:
					set {Fire.Power3.Campfire.Display.%{_uuid}%} to "&6🥾 &b%{Fire.Power3.Campfire.Second.%{_uuid}%}%s"

				else:
					set {Fire.Power3.Campfire.Display.%{_uuid}%} to "&6🥾 &b%{Fire.Power3.Campfire.Minute.%{_uuid}%}%m %{Fire.Power3.Campfire.Second.%{_uuid}%}%s"

			if {Fire.Power3.Campfire.Cooldown.%{_uuid}%} is true:
				remove 1 from {Fire.Power3.Campfire.Second.%{_uuid}%}


			
			if {Fire.Power3.Campfire.Second.%{_uuid}%} is -1:
				remove 1 from {Fire.Power3.Campfire.Minute.%{_uuid}%}
				set {Fire.Power3.Campfire.Second.%{_uuid}%} to 59
                
			if {Fire.Power3.Campfire.Minute.%{_uuid}%} is -1:
				set {Fire.Power3.Campfire.Cooldown.%{_uuid}%} to false
				set {Fire.Power3.Campfire.Second.%{_uuid}%} to 0
				set {Fire.Power3.Campfire.Minute.%{_uuid}%} to 0
				set {Fire.Power3.Campfire.Display.%{_uuid}%} to "&6🥾 &aReady!"


			#Enchanting

			if {Fire.Power2.Enchanting.Second.%{_uuid}%} is not set:
				set {Fire.Power2.Enchanting.Second.%{_uuid}%} to 14
				set {Fire.Power2.Enchanting.Minute.%{_uuid}%} to 59
				set {Fire.Power2.Enchanting.Cooldown.%{_uuid}%} to true

			if {Fire.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				set {Fire.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Fire.Power2.Enchanting.Minute.%{_uuid}%}%m %{Fire.Power2.Enchanting.Second.%{_uuid}%}%s"
			
			if {Fire.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				if {Fire.Power2.Enchanting.Minute.%{_uuid}%} is 0:
					set {Fire.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Fire.Power2.Enchanting.Second.%{_uuid}%}%s"

				else:
					set {Fire.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Fire.Power2.Enchanting.Minute.%{_uuid}%}%m %{Fire.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Fire.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				remove 1 from {Fire.Power2.Enchanting.Second.%{_uuid}%}


			
			if {Fire.Power2.Enchanting.Second.%{_uuid}%} is -1:
				remove 1 from {Fire.Power2.Enchanting.Minute.%{_uuid}%}
				set {Fire.Power2.Enchanting.Second.%{_uuid}%} to 59
                
			if {Fire.Power2.Enchanting.Minute.%{_uuid}%} is -1:
				set {Fire.Power2.Enchanting.Cooldown.%{_uuid}%} to false
				set {Fire.Power2.Enchanting.Display.%{_uuid}%} to "&aReady!"



			#Fireball





			if {Fire.Power1.Fireball.Cooldown.%{_uuid}%} is true:
				remove 1 from {Fire.Power1.Fireball.Second.%{_uuid}%}


			
			if {Fire.Power1.Fireball.Second.%{_uuid}%} is -1:
				remove 1 from {Fire.Power1.Fireball.Minute.%{_uuid}%}
				set {Fire.Power1.Fireball.Second.%{_uuid}%} to 59


			if {Fire.Power1.Fireball.Cooldown.%{_uuid}%} is true:
				if {Fire.Power1.Fireball.Minute.%{_uuid}%} is 0:
					set {Fire.Power1.Fireball.Display.%{_uuid}%} to "&6🧨 &b%{Fire.Power1.Fireball.Second.%{_uuid}%}%s"

				else:
					set {Fire.Power1.Fireball.Display.%{_uuid}%} to "&6🧨 &b%{Fire.Power1.Fireball.Minute.%{_uuid}%}%m %{Fire.Power1.Fireball.Second.%{_uuid}%}%s"


			if {Fire.Power1.Fireball.Second.%{_uuid}%} is not set:
				set {Fire.Power1.Fireball.Second.%{_uuid}%} to 0
				set {Fire.Power1.Fireball.Minute.%{_uuid}%} to 0

			if {Fire.Power1.Fireball.Display.%{_uuid}%} is not set:
				set {Fire.Power1.Fireball.Display.%{_uuid}%} to "&6🧨 &b%{Fire.Power1.Fireball.Minute.%{_uuid}%}%m %{Fire.Power1.Fireball.Second.%{_uuid}%}%s"

                



			if {Fire.Power1.Fireball.Minute.%{_uuid}%} is -1:
				set {Fire.Power1.Fireball.Cooldown.%{_uuid}%} to false

				set {Fire.Power1.Fireball.Display.%{_uuid}%} to "&6🧨 &aReady!"






				
			    




















on sneak toggle:
	set {_uuid} to uuid of player
	if {Tag..%player%} is 0:
		if player's off hand item is prismarine shard named "&6&lFire &lgem":
			if {Fire.Power2.Enchanting.Cooldown.%{_uuid}%} is not true:
				if player's held item is a any sword:
					execute console command "enchant %player% fire_aspect 2"
					send "&aEnchanting Tool with &eFire aspect &42"
					set {Fire.Power2.Enchanting.Minute.%{_uuid}%} to 14
					set {Fire.Power2.Enchanting.Second.%{_uuid}%}  to 59
					set {Fire.Power2.Enchanting.Cooldown.%{_uuid}%} to true
		
		if player's off hand item is amethyst shard named "&6&lFire &lgem":
			if {Tier2.Stregnth.%player%} is not true:
				if {Fire.Power2.Enchanting.Cooldown.%{_uuid}%} is not true:
					if player's held item is a any sword:
						execute console command "enchant %player% fire_aspect 1"
						send "&aEnchanting Tool with &eFire aspect &41"
						set {Fire.Power2.Enchanting.Minute.%{_uuid}%} to 14
						set {Fire.Power2.Enchanting.Second.%{_uuid}%}  to 59
						set {Fire.Power2.Enchanting.Cooldown.%{_uuid}%} to true



on drop prismarine shard:
	if event-item is prismarine shard named "&6&lFire &lgem":
		cancel event
on drop amethyst shard:
	if event-item is amethyst shard named "&6&lFire &lgem":
		cancel event
		
every 0.1 tick:
	loop all players:
		if {Fireball.%loop-player%} > 0:
			execute console command "execute as %loop-player% at @s run execute as @e[type=armor_stand,tag=5%loop-player%] run tp ~ ~1 ~"
			execute console command "execute as %loop-player% at @s run particle dust 1 0.42 0 1.4 ~ ~.2 ~ 0.2 0.2 0.2 0 5 force @a"

on right click:
	if player's held item is a prismarine shard named "&6&lFire &lgem":
		if clicked block is not air:
			if block above clicked block is air:
				set {_uuid} to uuid of player
				if {Fire.Power3.Campfire.Cooldown.%{_uuid}%} is false:
					set {Fire.Power3.Campfire.Second.%{_uuid}%} to 59
					set {Fire.Power3.Campfire.Minute.%{_uuid}%} to 1
					set {Fire.Power3.Campfire.Cooldown.%{_uuid}%} to true
					set block above clicked block to soul campfire
					send "&9Cozy campfire"
					execute console command "tag add %player% TrustedBy%player%"
					wait 15 seconds
					set block above clicked block to air

every 1 second:
	loop all players:
		if blocks in radius 4 of loop-player contains soul campfire:
			execute console command "execute as %loop-player% at @s run effect give @s saturation 1 0 true"
			execute console command "execute as %loop-player% at @s run effect give @s regeneration 1 0 true"


on left click:
	if player's held item is a prismarine shard named "&6&lFire &lgem":
		set {_uuid} to uuid of player
		if {Tag..%player%} is 0:
			if {Fire.Power1.Fireball.Cooldown.%{_uuid}%} is not true:
				wait 1 tick
				send "&6🔮 &bYou are Charging a &6Fireball"
				execute console command "execute as %player% at @s run summon armor_stand ~ ~ ~ {Tags:[""5%player%""],Invisible:1b,Marker:1b}"
				execute console command "execute as %player% at @s run item replace entity @e[type=armor_stand,distance=0..2] armor.head with fire_charge"
				make last spawned entity ride player

				if {Bliss.Fire.%player%} > 4:
					set {Fire.Power1.Fireball.Minute.%{_uuid}%} to 0
					set {Fire.Power1.Fireball.Second.%{_uuid}%} to 45
					set {Fire.Power1.Fireball.Cooldown.%{_uuid}%} to true

				if {Bliss.Fire.%player%} is 3:
					set {Fire.Power1.Fireball.Minute.%{_uuid}%} to 1
					set {Fire.Power1.Fireball.Second.%{_uuid}%} to 1
					set {Fire.Power1.Fireball.Cooldown.%{_uuid}%} to true

				if {Bliss.Fire.%player%} < 3:
					set {Fire.Power1.Fireball.Minute.%{_uuid}%} to 1
					set {Fire.Power1.Fireball.Second.%{_uuid}%} to 25
					set {Fire.Power1.Fireball.Cooldown.%{_uuid}%} to true
				 
				set {Fireball.%player%} to 1
				send "&610%% Charged" to player
				wait 3 second
				if {Fireball.%player%} is 1:
					set {Fireball.%player%} to 2
					send "&620%% Charged" to player
				wait 3 second
				if {Fireball.%player%} is 2:
					set {Fireball.%player%} to 3
					send "&630%% Charged" to player
				wait 3 second
				if {Fireball.%player%} is 3:
					set {Fireball.%player%} to 4
					send "&640%% Charged" to player
				wait 3 second
				if {Fireball.%player%} is 4:
					set {Fireball.%player%} to 5
					send "&650%% Charge" to player
				wait 3 second
				if {Fireball.%player%} is 5:
					set {Fireball.%player%} to 6
					send "&660%% Charge" to player
				wait 3 second
				if {Fireball.%player%} is 6:
					set {Fireball.%player%} to 7
					send "&670%% Charge" to player
				wait 3 second
				if {Fireball.%player%} is 7:
					set {Fireball.%player%} to 8
					send "&680%% Charge" to player
				wait 3 second
				if {Fireball.%player%} is 8:
					set {Fireball.%player%} to 9
					send "&690%% Charge" to player
				wait 3 second
				if {Fireball.%player%} is 9:
					set {Fireball.%player%} to 10
					send "&6100%% Charge" to player
		
on damage:
	if damage cause is Fireball:
		chance of 80%
		push victim up at speed 2.5
		push victim backwards at speed 1.2

every 1 tick:
	loop all players:
		if loop-player's offhand item is a prismarine shard named "&6&lFire &lgem":
			if loop-player has raw iron:
				remove 1 raw iron from loop-player
				give loop-player 1 iron ingot
			if loop-player has raw gold:
				remove 1 raw gold from loop-player
				give loop-player 1 gold ingot
			if loop-player has mutton:
				remove 1 mutton from loop-player
				give loop-player 1 cooked mutton
			if loop-player has cobblestone:
				remove 1 cobblestone from loop-player
				give loop-player 1 stone
		if loop-player's offhand item is a amethyst shard named "&6&lFire &lgem":
			if loop-player has raw iron:
				remove 1 raw iron from loop-player
				give loop-player 1 iron ingot
			if loop-player has raw gold:
				remove 1 raw gold from loop-player
				give loop-player 1 gold ingot
			if loop-player has mutton:
				remove 1 mutton from loop-player
				give loop-player 1 cooked mutton
			if loop-player has cobblestone:
				remove 1 cobblestone from loop-player
				give loop-player 1 stone
				
on damage:
	if {zerodamage..%victim%} is true:
		cancel event

on left click:
	if player's held item is a prismarine shard named "&6&lFire &lgem":
		set {_uuid} to uuid of player
		if {Tag..%player%} is 0:
			if {Fireball.%player%} is 1:
				set {Fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:2}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {Fireball.%player%} is 2:
				set {Fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:2}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {Fireball.%player%} is 3:
				set {Fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:2.4}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {Fireball.%player%} is 4:
				set {Fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:2.7}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {Fireball.%player%} is 5:
				set {Fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:3.4}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {Fireball.%player%} is 6:
				set {Fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:3.8}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {Fireball.%player%} is 7:
				set {Fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:3.8}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {Fireball.%player%} is 8:
				set {Fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:4.4}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {Fireball.%player%} is 9:
				set {Fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:5.2}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {Fireball.%player%} is 10:
				set {Fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:5.8}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false