on respawn:

	if {Bliss.Fire.%player%} is 1:
		give player amethyst shard with custom model data 95 named "&6&lFire &lgem" with lore "&8Broken Gem", "&aAuto Smelt if gem is in off hand", "enchant's sword with fire aspect 1/2" and "&6Fireball Can Charge for 4 seconds" and "<red>" 
	if {Bliss.Fire.%player%} is 2:
		give player amethyst shard with custom model data 81 named "&6&lFire &lgem" with lore "&cRuined Gem", "&aAuto Smelt if gem is in off hand", "enchant's sword with fire aspect 1/2" and "&6Fireball Can Charge for 4 seconds" and "<red>" 
	if {Bliss.Fire.%player%} is 3:
		give player amethyst shard with custom model data 61 named "&6&lFire &lgem" with lore "&eDamaged Gem", "&aAuto Smelt if gem is in off hand", "enchant's sword with fire aspect 1/2" and "&6Fireball Can Charge for 4 seconds" and "<red>" 
	if {Bliss.Fire.%player%} is 4:
		give player amethyst shard with custom model data 41 named "&6&lFire &lgem" with lore "&aCracked Gem", "&aAuto Smelt if gem is in off hand", "enchant's sword with fire aspect 1/2" and "&6Fireball Can Charge for 4 seconds" and "<red>" 
	if {Bliss.Fire.%player%} is 5:
		give player amethyst shard with custom model data 21 named "&6&lFire &lgem" with lore "&aScratched Gem", "&aAuto Smelt if gem is in off hand", "enchant's sword with fire aspect 1/2" and "&6Fireball Can Charge for 4 seconds" and "<red>" 
	if {Bliss.Fire.%player%} is 6:
		give player amethyst shard with custom model data 1 named "&6&lFire &lgem" with lore "&bPristine Gem", "&aAuto Smelt if gem is in off hand", "enchant's sword with fire aspect 1/2" and "&6Fireball Can Charge for 4 seconds" and "<red>" 
