on death of player:
	if attacker's off hand item is a prismarine shard named "&f&lPuff &lgem":
		add 1 to {Bliss.Puff.%attacker%} 
		if {Bliss.Puff.%attacker%} is 1:
			set attacker's off hand item to a prismarine shard named "&f&lPuff &lgem" with lore "&4Broken Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" with custom model data 98
		if {Bliss.Puff.%attacker%} is 2:
			set attacker's off hand item to a prismarine shard named "&f&lPuff &lgem" with lore "&cRuined Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" with custom model data 1901
		if {Bliss.Puff.%attacker%} is 3:
			set attacker's off hand item to a prismarine shard named "&f&lPuff &lgem" with lore "&dDamaged Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" with custom model data 1902
		if {Bliss.Puff.%attacker%} is 4:
			set attacker's off hand item to a prismarine shard named "&f&lPuff &lgem" with lore "&aCracked Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" with custom model data 1903
		if {Bliss.Puff.%attacker%} is 5:
			set attacker's off hand item to a prismarine shard named "&f&lPuff &lgem" with lore "&aScratched Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" with custom model data 1904
		if {Bliss.Puff.%attacker%} is 6:
			set attacker's off hand item to a prismarine shard named "&f&lPuff &lgem" with lore "&bPristine Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" with custom model data 1905
		if {Bliss.Puff.%attacker%} is 7:
			set attacker's off hand item to a prismarine shard named "&f&lPuff &lgem" with lore "&bPristine + Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" with custom model data 1905
		if {Bliss.Puff.%attacker%} is 8:
			set attacker's off hand item to a prismarine shard named "&f&lPuff &lgem" with lore "&bPristine + 2 Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" with custom model data 1905
		if {Bliss.Puff.%attacker%} is 9:
			set attacker's off hand item to a prismarine shard named "&f&lPuff &lgem" with lore "&bPristine + 3 Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" with custom model data 1905
		if {Bliss.Puff.%attacker%} is 10:
			set attacker's off hand item to a prismarine shard named "&f&lPuff &lgem" with lore "&bPristine + 4 Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" with custom model data 1905
		if {Bliss.Puff.%attacker%} is 11:
			set {item} to prismarine shard with custom model data 6 named "&f&lPuff &lgem" with lore "&bPristine + 5 Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
			set attacker's off hand item to {item}
			enchant {item} with mending 1
