#Gem Strength Powers

every 1 second:
	loop all players:
		if loop-player's off hand item is a amethyst shard named "&4&lStrength &e&lgem":
			if {Tier2.Stregnth.%loop-player%} is not true:
				if {strength.cooldown.%loop-player%} is not true:
					send action bar "&4🗡 &aReady!" to loop-player
				if {strength.cooldown.%loop-player%} is true:
					send action bar "&4🗡 &b%{StrengthMin.%loop-player%}%m %{StrengthSec.%loop-player%}%s" to loop-player
		if loop-player is holding amethyst shard named "&4&lStrength &e&lgem":
			if {Tier2.Stregnth.%loop-player%} is not true:
				if {strength.cooldown.%loop-player%} is not true:
					send action bar "&c🔺 &aReady!" to loop-player
				if {strength.cooldown.%loop-player%} is true:
					send action bar "&c🔺 &b%{StrengthMin.%loop-player%}%m %{StrengthSec.%loop-player%}%s" to loop-player
		if {Bliss.Strength.%loop-player%} > 3:
			if {Tier2.Stregnth.%loop-player%} is not true:
				execute console command "effect give %loop-player% strength 2 0 true"
			if {Tier2.Stregnth.%loop-player%} is true:
				execute console command "effect give %loop-player% strength 2 1 true"
		if loop-player is holding prismarine shard named "&4&lStrength &e&lgem":
			if {Tier2.Stregnth.%loop-player%} is not true:
				if {strength.cooldown.%loop-player%} is not true:
					send action bar "&c🔺 &aReady!" to loop-player
				if {strength.cooldown.%loop-player%} is true:
					send action bar "&c🔺 &b%{StrengthMin.%loop-player%}%m %{StrengthSec.%loop-player%}%s" to loop-player
			if {Tier2.Stregnth.%loop-player%} is true:
				if {strength.cooldown.%loop-player%} is not true:
					if {strength.cooldown2.%loop-player%} is not true:
						if {strength.cooldown3.%loop-player%} is not true:
							send action bar "🤺 &aReady! &c🔮 &aReady! &c⚔ &aReady!" to loop-player
						if {strength.cooldown3.%loop-player%} is true:
							send action bar "🤺 &aReady! &c🔮 &aReady! &c⚔ &b%{StrengthMin3.%loop-player%}%m %{StrengthSec3.%loop-player%}%s" to loop-player
				if {strength.cooldown.%loop-player%} is not true:
					if {strength.cooldown2.%loop-player%} is true:
						if {strength.cooldown3.%loop-player%} is true:
							send action bar "🤺 &b%{StrengthMin2.%loop-player%}%m %{StrengthSec2.%loop-player%}%s &c🔮 &aReady! &c⚔ &b%{StrengthMin3.%loop-player%}%m %{StrengthSec3.%loop-player%}%s" to loop-player
						if {strength.cooldown3.%loop-player%} is not true:
							send action bar "🤺 &b%{StrengthMin2.%loop-player%}%m %{StrengthSec2.%loop-player%}%s &c🔮 &aReady! &c⚔ &aReady!" to loop-player
				if {strength.cooldown.%loop-player%} is true:
					if {strength.cooldown2.%loop-player%} is true:
						if {strength.cooldown3.%loop-player%} is true:
							send action bar "🤺 &b%{StrengthMin2.%loop-player%}%m %{StrengthSec2.%loop-player%}%s &c🔮 &b%{StrengthMin.%loop-player%}%m %{StrengthSec.%loop-player%}%s &c⚔ &b%{StrengthMin3.%loop-player%}%m %{StrengthSec3.%loop-player%}%s" to loop-player
						if {strength.cooldown3.%loop-player%} is not true:
							send action bar "🤺 &b%{StrengthMin2.%loop-player%}%m %{StrengthSec2.%loop-player%}%s &c🔮 &b%{StrengthMin.%loop-player%}%m %{StrengthSec.%loop-player%}%s &c⚔ &aReady!" to loop-player
				if {strength.cooldown.%loop-player%} is true:
					if {strength.cooldown2.%loop-player%} is not true:
						if {strength.cooldown3.%loop-player%} is not true:
							send action bar "🤺 &a!Ready &c🔮 &b%{StrengthMin.%loop-player%}%m %{StrengthSec.%loop-player%}%s &c⚔ &a!Ready" to loop-player
						if {strength.cooldown3.%loop-player%} is true:
							send action bar "🤺 &aReady! &4🗡 &b%{StrengthMin.%loop-player%}%m %{StrengthSec.%loop-player%}%s &c⚔ &b%{StrengthMin3.%loop-player%}%m %{StrengthSec3.%loop-player%}%s" to loop-player

		if loop-player's off hand item is a prismarine shard named "&4&lStrength &e&lgem":
			if {Tier2.Stregnth.%loop-player%} is true:
				if {strength.cooldown.%loop-player%} is not true:
					if {strength.cooldown2.%loop-player%} is not true:
						if {strength.cooldown3.%loop-player%} is not true:
							send action bar "🤺 &aReady! &c🔮 &aReady! &c⚔ &aReady!" to loop-player
						if {strength.cooldown3.%loop-player%} is true:
							send action bar "🤺 &aReady! &c🔮 &aReady! &c⚔ &b%{StrengthMin3.%loop-player%}%m %{StrengthSec3.%loop-player%}%s" to loop-player
				if {strength.cooldown.%loop-player%} is not true:
					if {strength.cooldown2.%loop-player%} is true:
						if {strength.cooldown3.%loop-player%} is true:
							send action bar "🤺 &b%{StrengthMin2.%loop-player%}%m %{StrengthSec2.%loop-player%}%s &c🔮 &aReady! &c⚔ &b%{StrengthMin3.%loop-player%}%m %{StrengthSec3.%loop-player%}%s" to loop-player
						if {strength.cooldown3.%loop-player%} is not true:
							send action bar "🤺 &b%{StrengthMin2.%loop-player%}%m %{StrengthSec2.%loop-player%}%s &c🔮 &aReady! &c⚔ &aReady!" to loop-player
				if {strength.cooldown.%loop-player%} is true:
					if {strength.cooldown2.%loop-player%} is true:
						if {strength.cooldown3.%loop-player%} is true:
							send action bar "🤺 &b%{StrengthMin2.%loop-player%}%m %{StrengthSec2.%loop-player%}%s &c🔮 &b%{StrengthMin.%loop-player%}%m %{StrengthSec.%loop-player%}%s &c⚔ &b%{StrengthMin3.%loop-player%}%m %{StrengthSec3.%loop-player%}%s" to loop-player
						if {strength.cooldown3.%loop-player%} is not true:
							send action bar "🤺 &b%{StrengthMin2.%loop-player%}%m %{StrengthSec2.%loop-player%}%s &c🔮 &b%{StrengthMin.%loop-player%}%m %{StrengthSec.%loop-player%}%s &c⚔ &aReady!" to loop-player
				if {strength.cooldown.%loop-player%} is true:
					if {strength.cooldown2.%loop-player%} is not true:
						if {strength.cooldown3.%loop-player%} is not true:
							send action bar "🤺 &aReady! &c🔮 &b%{StrengthMin.%loop-player%}%m %{StrengthSec.%loop-player%}%s &c⚔ &a!Ready" to loop-player
						if {strength.cooldown3.%loop-player%} is true:
							send action bar "🤺 &aReady! &c🔮 &b%{StrengthMin.%loop-player%}%m %{StrengthSec.%loop-player%}%s &c⚔ &b%{StrengthMin3.%loop-player%}%m %{StrengthSec3.%loop-player%}%s" to loop-player

		if loop-player has a prismarine shard named "&4&lStrength &e&lgem":
			remove 1 from {StrengthSec.%loop-player%}
			remove 1 from {StrengthSec2.%loop-player%}
			remove 1 from {StrengthSec3.%loop-player%}
			if {StrengthSec.%loop-player%} is -1:
				remove 1 from {StrengthMin.%loop-player%}
				set {StrengthSec.%loop-player%} to 59
				if {StrengthMin.%loop-player%} is -1:
					set {strength.cooldown.%loop-player%} to false
			if {StrengthSec2.%loop-player%} is -1:
				remove 1 from {StrengthMin2.%loop-player%}
				set {StrengthSec2.%loop-player%} to 59
				if {StrengthMin2.%loop-player%} is -1:
					set {strength.cooldown2.%loop-player%} to false
			if {StrengthSec3.%loop-player%} is -1:
				remove 1 from {StrengthMin3.%loop-player%}
				set {StrengthSec3.%loop-player%} to 59
				if {StrengthMin3.%loop-player%} is -1:
					set {strength.cooldown3.%loop-player%} to false
		if loop-player has a amethyst shard named "&4&lStrength &e&lgem":
			remove 1 from {StrengthSec.%loop-player%}
			remove 1 from {StrengthSec2.%loop-player%}
			remove 1 from {StrengthSec3.%loop-player%}
			if {StrengthSec.%loop-player%} is -1:
				remove 1 from {StrengthMin.%loop-player%}
				set {StrengthSec.%loop-player%} to 59
				if {StrengthMin.%loop-player%} is -1:
					set {strength.cooldown.%loop-player%} to false
			if {StrengthSec2.%loop-player%} is -1:
				remove 1 from {StrengthMin2.%loop-player%}
				set {StrengthSec2.%loop-player%} to 59
				if {StrengthMin2.%loop-player%} is -1:
					set {strength.cooldown2.%loop-player%} to false
			if {StrengthSec3.%loop-player%} is -1:
				remove 1 from {StrengthMin3.%loop-player%}
				set {StrengthSec3.%loop-player%} to 59
				if {StrengthMin3.%loop-player%} is -1:
					set {strength.cooldown3.%loop-player%} to false

on sneak toggle:
	if {Tag..%player%} is 0:
		if player's off hand item is a amethyst shard named "&4&lStrength &e&lgem":
			if {Tier2.Stregnth.%player%} is not true:
				execute console command "enchant %player% sharpness 2"
				send "&aEnchanting Tool with &csharpness &42"
				set {StrengthMin.%player%} to 1
				set {StrengthSec.%player%} to 59
				set {strength.cooldown.%player%} to true
		if player's off hand item is a prismarine shard named "&4&lStrength &e&lgem":
			if {Tier2.Stregnth.%player%} is true:
				if player's held item is any sword:
					enchant the player's tool with sharpness 5
					send "&c🔮 &bEnchanting Tool"
				if player's held item is any axe:
					enchant the player's tool with sharpness 5
					send "&c🔮 &bEnchanting Tool"
				set {StrengthMin.%player%} to 1
				set {StrengthSec.%player%} to 59
				set {strength.cooldown.%player%} to true
on damage:
	if {Tag..%attacker%} is 0:
		if {Bliss.Strength.%attacker%} > 0:
			if attacker's off hand item is a prismarine shard named "&4&lStrength &e&lgem":
				if attacker's health < 3:
					add 8 to damage
				if attacker's health is 3:
					add 4.5 to damage
				if attacker's health is 3.5:
					add 4 to damage
				if attacker's health is 4:
					add 3.5 to damage
				if attacker's health is 4.5:
					add 2.5 to damage
				if attacker's health is 5:
					add 2 to damage
				if attacker's health is 5.5:
					add 1.5 to damage
				if attacker's health is 6:
					add 1 to damage
				if attacker's health is 6.5:
					add 0.5 to damage
			if attacker's off hand item is a amethyst shard named "&4&lStrength &e&lgem":
				if attacker's health < 2:
					add 6 to damage
				if attacker's health is 2.5:
					add 5.5 to damage
				if attacker's health is 3:
					add 4.5 to damage
				if attacker's health is 3.5:
					add 4 to damage
				if attacker's health is 4:
					add 3.5 to damage
				if attacker's health is 4.5:
					add 2.5 to damage
				if attacker's health is 5:
					add 2 to damage
				if attacker's health is 5.5:
					add 1.5 to damage
				if attacker's health is 6:
					add 1 to damage
				if attacker's health is 6.5:
					add 0.5 to damage



on right click on entity:
	if {Tag..%player%} is 0:
		if player's held item is a prismarine shard named "&4&lStrength &e&lgem":
			if {Tier2.Stregnth.%player%} is true:
				if event-entity is a player:
					if {strength.cooldown2.%player%} is not true:
						send "&byou used &4Frailer &fon &4%event-entity%" to player
						send "&byou have been affected by &4Frailer &bfrom %player%" to event-entity
						execute console command "effect clear %event-entity%"
						apply weakness to event-entity for 20 seconds
						execute player command "/strengthcircle 0.5"
						execute player command "/strengthcircle 1"
						execute player command "/strengthcircle 1.5"
						execute player command "/strengthcircle 2"
						execute player command "/strengthcircle 2.5"
						execute player command "/strengthcircle 3"
						execute player command "/strengthcircle 3.5"
						if {Bliss.Strength.%player%} > 4:
							set {StrengthMin2.%player%} to 1
							set {StrengthSec2.%player%} to 15
							set {strength.cooldown2.%player%} to true
						if {Bliss.Strength.%player%} is 3:
							set {StrengthMin2.%player%} to 1
							set {StrengthSec2.%player%} to 45
							set {strength.cooldown2.%player%} to true
						if {Bliss.Strength.%player%} < 3:
							set {StrengthMin2.%player%} to 2
							set {StrengthSec2.%player%} to 25
							set {strength.cooldown2.%player%} to true

                            

on drop prismarine shard:
	if event-item is prismarine shard named "&4&lStrength &e&lgem":
		cancel event
on drop amethyst shard:
	if event-item is amethyst shard named "&4&lStrength &e&lgem":
		cancel event

every 4 ticks:
	loop all players:
		if {ChadStrength..%loop-player%} is true:
			draw 5 of dust using dustOption(dark red, 1) at loop-player
			execute console command "execute as %loop-player% at @s run particle dust 0.33 0.33 0.33 1 ^ ^.7 ^1 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0.33 0.33 0.33 1 ^ ^.7 ^-1 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0.33 0.33 0.33 1 ^1 ^.7 ^ 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0.33 0.33 0.33 1 ^-1 ^.7 ^ 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0 0 0 1 ^ ^.7 ^1 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0 0 0 1 ^ ^.7 ^-1 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0 0 0 1 ^1 ^.7 ^ 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0 0 0 1 ^-1 ^.7 ^ 0 0 0 0 10 force @a"


on damage:
	if {dmg..%attacker%} > 11:
		set {dmg..%attacker%} to 12
	if {ChadStrength..%attacker%} is true:
		fall distance of attacker is less than 0.7:
			if {dmg..%attacker%} > 14:
				set {dmg..%attacker%} to 14
			if {Test.Double.%attacker%} is 3:
				add {dmg..%attacker%} to damage
				set {dmg..%attacker%} to damage
				set {Test.Double.%attacker%} to 0
				set {ChadSkill...%attacker%} to false
				set {ChadSkill...%attacker%} to false
				set {ChadStrength..%attacker%} to false
			if {Test.Double.%attacker%} is 2:
				set {dmg..%attacker%} to damage
				add 1 to {Test.Double.%attacker%}
			if {Test.Double.%attacker%} is 1:
				set {dmg..%attacker%} to damage
				add 1 to {Test.Double.%attacker%}
			if {Test.Double.%attacker%} < 1:
				set {dmg..%attacker%} to damage
				add 1 to {Test.Double.%attacker%}




on left click:
	if {Tag..%player%} is 0:
		if player's held item is a prismarine shard named "&4&lStrength &e&lgem":
			if {Tier2.Stregnth.%player%} is true:
				if {strength.cooldown3.%player%} is not true:
					set {Test.Double.%player%} to 0
					send "&4⚔&cYou activated &4Chad Strength &bGroup"
					set {Doubledamage.%player%} to -5
					set {ChadStrength..%player%} to true
					if {Bliss.Strength.%player%} > 4:
						set {StrengthMin3.%player%} to 2
						set {StrengthSec3.%player%} to 30
						set {strength.cooldown3.%player%} to true
					if {Bliss.Strength.%player%} is 3:
						set {StrengthMin3.%player%} to 3
						set {StrengthSec3.%player%} to 1
						set {strength.cooldown3.%player%} to true
					if {Bliss.Strength.%player%} < 3:
						set {StrengthMin3.%player%} to 3
						set {StrengthSec3.%player%} to 35
						set {strength.cooldown3.%player%} to true
					
			if {ChadStrength..%player%} is true:
				set {ChadStrength...%player%} to true


on left click:
	if {Tag..%player%} is 0:
		if player has a prismarine shard named "&4&lStrength &e&lgem":
			if {Tier2.Stregnth.%player%} is true:
				if {strength.cooldown3.%player%} is not true:
					wait 10 seconds 
					set {ChadStrength...%player%} to false
					set {ChadStrength..%player%} to false

every 1 second:
	loop all players:
		if loop-player's off hand item is a amethyst shard named "&4&lStrength &e&lgem":
			apply potion of strength of tier 1 to loop-player for 1.03 seconds

		if loop-player's held item is a amethyst shard named "&4&lStrength &e&lgem":
			apply potion of strength of tier 1 to loop-player for 1.03 seconds

		if loop-player's off hand item is a prismarine shard named "&4&lStrength &e&lgem":
			apply potion of strength of tier 2 to loop-player for 1.03 seconds

		if loop-player's held item is a prismarine shard named "&4&lStrength &e&lgem":
			apply potion of strength of tier 2 to loop-player for 1.03 seconds