#Wealth Powers


every 1 second:
	loop all players:
		if loop-player's off hand item is a amethyst shard named "&2&lWealth &lgem":
			if {Tier2.Stregnth.%loop-player%} is not true:
				if {wealth.cooldown.%loop-player%} is not true:
					send action bar "&2$ &aReady!" to loop-player
				if {wealth.cooldown.%loop-player%} is true:
					send action bar "&2$ &b%{WealthMin.%loop-player%}%m %{WealthSec.%loop-player%}%s" to loop-player
			if {Bliss.Wealth.%loop-player%} > 2:
				execute console command "effect give %loop-player% hero_of_the_village 2 0"
		if loop-player is holding amethyst shard named "&2&lWealth &lgem":
			if {Tier2.Stregnth.%loop-player%} is not true:
				if {wealth.cooldown.%loop-player%} is not true:
					send action bar "&2$ &aReady!" to loop-player
				if {wealth.cooldown.%loop-player%} is true:
					send action bar "&2$ &b%{WealthMin.%loop-player%}%m %{WealthSec.%loop-player%}%s" to loop-player
			if {Bliss.Wealth.%loop-player%} > 2:
				execute console command "effect give %loop-player% hero_of_the_village 2 0"
		if loop-player's off hand item is a prismarine shard named "&2&lWealth &lgem":
			if {Bliss.Wealth.%loop-player%} > 2:
				execute console command "effect give %loop-player% hero_of_the_village 2 1"
			if {Tier2.Stregnth.%loop-player%} is true:
				if {wealth.cooldown.%loop-player%} is not true:
					if {wealth.cooldown2.%loop-player%} is not true:
						if {wealth.cooldown3.%loop-player%} is not true:
							send action bar "💸 &aReady! &2🔮 &aReady! 🍀 &aReady!" to loop-player
						if {wealth.cooldown3.%loop-player%} is true:
							send action bar "💸 &aReady! &2🔮 &aReady! 🍀 &b%{WealthMin3.%loop-player%}%m %{WealthSec3.%loop-player%}%s" to loop-player
				if {wealth.cooldown.%loop-player%} is not true:
					if {wealth.cooldown2.%loop-player%} is true:
						if {wealth.cooldown3.%loop-player%} is true:
							send action bar "💸 &b%{WealthMin2.%loop-player%}%m %{WealthSec2.%loop-player%}%s &2🔮 &aReady! 🍀 &b%{WealthMin3.%loop-player%}%m %{WealthSec3.%loop-player%}%s" to loop-player
						if {wealth.cooldown3.%loop-player%} is not true:
							send action bar "💸 &b%{WealthMin2.%loop-player%}%m %{WealthSec2.%loop-player%}%s &2🔮 &aReady! 🍀 &aReady!" to loop-player
				if {wealth.cooldown.%loop-player%} is true:
					if {wealth.cooldown2.%loop-player%} is true:
						if {wealth.cooldown3.%loop-player%} is true:
							send action bar "💸 &b%{WealthMin2.%loop-player%}%m %{PuffSec2.%loop-player%}%s &2🔮 &b%{WealthMin.%loop-player%}%m %{WealthSec.%loop-player%}%s 🍀 &b%{WealthMin3.%loop-player%}%m %{WealthSec3.%loop-player%}%s" to loop-player
						if {wealth.cooldown3.%loop-player%} is not true:
							send action bar "💸 &b%{WealthMin2.%loop-player%}%m %{WealthSec2.%loop-player%}%s &2🔮 &b%{WealthMin.%loop-player%}%m %{WealthSec.%loop-player%}%s 🍀 &aReady!" to loop-player
				if {wealth.cooldown.%loop-player%} is true:
					if {wealth.cooldown2.%loop-player%} is not true:
						if {wealth.cooldown3.%loop-player%} is not true:
							send action bar "💸 &aReady! &2🔮 &b%{WealthMin.%loop-player%}%m %{WealthSec.%loop-player%}%s 🍀 &aReady!" to loop-player
						if {wealth.cooldown3.%loop-player%} is true:
							send action bar "💸 &aReady! &2🔮 &b%{WealthMin.%loop-player%}%m %{WealthSec.%loop-player%}%s 🍀 &b%{WealthMin3.%loop-player%}%m %{WealthSec3.%loop-player%}%s" to loop-player

		if loop-player's held item is a prismarine shard named "&2&lWealth &lgem":
			if {Bliss.Wealth.%loop-player%} > 2:
				execute console command "effect give %loop-player% hero_of_the_village 2 1"
			if {Tier2.Stregnth.%loop-player%} is true:
				if {wealth.cooldown.%loop-player%} is not true:
					if {wealth.cooldown2.%loop-player%} is not true:
						if {wealth.cooldown3.%loop-player%} is not true:
							send action bar "💸 &aReady! &2🔮 &aReady! 🍀 &aReady!" to loop-player
						if {wealth.cooldown3.%loop-player%} is true:
							send action bar "💸 &aReady! &2🔮 &aReady! 🍀 &b%{WealthMin3.%loop-player%}%m %{WealthSec3.%loop-player%}%s" to loop-player
				if {wealth.cooldown.%loop-player%} is not true:
					if {wealth.cooldown2.%loop-player%} is true:
						if {wealth.cooldown3.%loop-player%} is true:
							send action bar "💸 &b%{WealthMin2.%loop-player%}%m %{WealthSec2.%loop-player%}%s &2🔮 &aReady! 🍀 &b%{WealthMin3.%loop-player%}%m %{WealthSec3.%loop-player%}%s" to loop-player
						if {wealth.cooldown3.%loop-player%} is not true:
							send action bar "💸 &b%{WealthMin2.%loop-player%}%m %{WealthSec2.%loop-player%}%s &2🔮 &aReady! 🍀 &aReady!" to loop-player
				if {wealth.cooldown.%loop-player%} is true:
					if {wealth.cooldown2.%loop-player%} is true:
						if {wealth.cooldown3.%loop-player%} is true:
							send action bar "💸 &b%{WealthMin2.%loop-player%}%m %{PuffSec2.%loop-player%}%s &2🔮 &b%{WealthMin.%loop-player%}%m %{WealthSec.%loop-player%}%s 🍀 &b%{WealthMin3.%loop-player%}%m %{WealthSec3.%loop-player%}%s" to loop-player
						if {wealth.cooldown3.%loop-player%} is not true:
							send action bar "💸 &b%{WealthMin2.%loop-player%}%m %{WealthSec2.%loop-player%}%s &2🔮 &b%{WealthMin.%loop-player%}%m %{WealthSec.%loop-player%}%s 🍀 &aReady!" to loop-player
				if {wealth.cooldown.%loop-player%} is true:
					if {wealth.cooldown2.%loop-player%} is not true:
						if {wealth.cooldown3.%loop-player%} is not true:
							send action bar "💸 &aReady! &2🔮 &b%{WealthMin.%loop-player%}%m %{WealthSec.%loop-player%}%s 🍀 &aReady!" to loop-player
						if {wealth.cooldown3.%loop-player%} is true:
							send action bar "💸 &aReady! &2🔮 &b%{WealthMin.%loop-player%}%m %{WealthSec.%loop-player%}%s 🍀 &b%{WealthMin3.%loop-player%}%m %{WealthSec3.%loop-player%}%s" to loop-player


		if loop-player has a prismarine shard named "&2&lWealth &lgem":
			remove 1 from {WealthSec.%loop-player%}
			remove 1 from {WealthSec2.%loop-player%}
			remove 1 from {WealthSec3.%loop-player%}
			if {WealthSec.%loop-player%} is -1:
				remove 1 from {WealthMin.%loop-player%}
				set {WealthSec.%loop-player%} to 59
				if {WealthMin.%loop-player%} is -1:
					set {wealth.cooldown.%loop-player%} to false
			if {WealthSec2.%loop-player%} is -1:
				remove 1 from {WealthMin2.%loop-player%}
				set {WealthSec2.%loop-player%} to 59
				if {WealthMin2.%loop-player%} is -1:
					set {wealth.cooldown2.%loop-player%} to false
			if {WealthSec3.%loop-player%} < 0:
				remove 1 from {WealthMin3.%loop-player%}
				set {WealthSec3.%loop-player%} to 59
				if {WealthMin3.%loop-player%} is -1:
					set {wealth.cooldown3.%loop-player%} to false
		if loop-player has a amethyst shard named "&2&lWealth &lgem":
			remove 1 from {WealthSec.%loop-player%}
			if {WealthSec.%loop-player%} is -1:
				remove 1 from {WealthfMin.%loop-player%}
				set {WealthSec.%loop-player%} to 59
				if {PuffMin.%loop-player%} is -1:
					set {wealth.cooldown.%loop-player%} to false


			
on drop prismarine shard:
	if event-item is prismarine shard named "&2&lWealth &lgem":
		cancel event
on drop amethyst shard:
	if event-item is amethyst shard named "&2&lWealth &lgem":
		cancel event	



on break diamond ore:
	if {orePerMine.%player%} < 4:
		add 1 to {orePerMine.%player%}
	if {orePerMine.%player%} is 3:
		set {orePerMine.%player%} to 0
		drop diamond
on break deepslate iron ore:
	if player's off hand item is a prismarine shard named "&2&lWealth &lgem":
		if {orePerMine.%player%} < 4:
			add 1 to {orePerMine.%player%}
		if {orePerMine.%player%} is 3:
			set {orePerMine.%player%} to 0
			drop raw iron
on break iron ore:
	if player's off hand item is a prismarine shard named "&2&lWealth &lgem":
		if {orePerMine.%player%} < 4:
			add 1 to {orePerMine.%player%}
		if {orePerMine.%player%} is 3:
			set {orePerMine.%player%} to 0
			drop raw iron
on break deepslate gold ore:
	if player's off hand item is a prismarine shard named "&2&lWealth &lgem":
		if {orePerMine.%player%} < 4:
			add 1 to {orePerMine.%player%}
		if {orePerMine.%player%} is 3:
			set {orePerMine.%player%} to 0
			drop raw gold
on break gold ore:
	if player's off hand item is a prismarine shard named "&2&lWealth &lgem":
		if {orePerMine.%player%} < 4:
			add 1 to {orePerMine.%player%}
		if {orePerMine.%player%} is 3:
			set {orePerMine.%player%} to 0
			drop raw gold
on break deepslate diamond ore:
	if player's off hand item is a prismarine shard named "&2&lWealth &lgem":
		if {orePerMine.%player%} < 4:
			add 1 to {orePerMine.%player%}
		if {orePerMine.%player%} is 3:
			set {orePerMine.%player%} to 0
			drop diamond
on break diamond ore:
	if player's off hand item is a prismarine shard named "&2&lWealth &lgem":
		if {orePerMine.%player%} < 4:
			add 1 to {orePerMine.%player%}
		if {orePerMine.%player%} is 3:
			set {orePerMine.%player%} to 0
			drop diamond

on sneak toggle:
	if player's off hand item is prismarine shard named "&2&lWealth &lgem":
		if {Tier2.Stregnth.%player%} is true:
			if {fire.cooldown2.%player%} is not true:
				if player's held item is a any pickaxe:
					execute console command "enchant %player% fortune 3"
					send "&aEnchanting Tool with &eFortune &43"
					set {WealthMin.%player%} to 1
					set {WealthSec.%player%} to 59
					set {wealth.cooldown.%player%} to true
	if player's off hand item is amethyst shard named "&2&lWealth &lgem":
		if {Tier2.Stregnth.%player%} is not true:
			if {fire.cooldown2.%player%} is not true:
				if player's held item is a any pickaxe:
					execute console command "enchant %player% fortune 1"
					send "&aEnchanting Tool with &eFortune &41"
					set {WealthMin.%player%} to 1
					set {WealthSec.%player%} to 59
					set {wealth.cooldown.%player%} to true


on right click:
	if player's held item is a prismarine shard named "&2&lWealth &lgem":
		if {Tag..%player%} is 0:
			set {RichRush..%player%} to true
			set {wealth.cooldown2.%player%} to true
			set {WealthMin2.%player%} to 29
			set {WealthSec2.%player%} to 59
			wait 5 minutes
			set {RichRush..%player%} to false

on break diamond ore:
	if {RichRush..%player%} is true:
		drop 3 diamond
on break deepslate diamond ore:
	if {RichRush..%player%} is true:
		drop 3 diamond
on break gold ore:
	if {RichRush..%player%} is true:
		drop 3 raw gold
on break deepslate gold ore:
	if {RichRush..%player%} is true:
		drop 3 raw gold
on break ancient debris:
	if {RichRush..%player%} is true:
		drop 1 netherite scrap
		
on right click on entity:
	if player's off hand item is a prismarine shard named "&2&lWealth &lgem":
		if {wealth.cooldown3.%player%} is not true:
			if {Tag..%player%} is 0:
				set {unfortunate...%event-entity%} to true
				send "&fYou have used &2Unfortunate &eon %event-entity%" to player
				send "You have been affected with &2Unfortunate &eby %player%" to event-entity
				execute console command "execute as %player% at @s run function particles:unfortunate1"
				if {Bliss.Wealth.%player%} > 4:
					set {wealth.cooldown3.%player%} to true
					set {WealthMin3.%player%} to 1
					set {WealthSec3.%player%} to 30
				if {Bliss.Wealth.%player%} is 3:
					set {wealth.cooldown3.%player%} to true
					set {WealthMin3.%player%} to 1
					set {WealthSec3.%player%} to 59
				if {Bliss.Wealth.%player%} < 3:
					set {wealth.cooldown3.%player%} to true
					set {WealthMin3.%player%} to 2
					set {WealthSec3.%player%} to 45
				wait 1 second
				execute console command "execute as %player% at @s run function particles:unfortunate2"
				execute console command "execute as %player% at @s run function particles:unfortunate2"
				execute console command "execute as %player% at @s run function particles:unfortunate2"
				wait 59 seconds
				set {unfortunate...%event-entity%} to false

on resurrect:
	if {unfortunate...%player%} is true:
		chance of 60%
		send "Its very &2unfortunate &fyour totem didn't work"
		cancel event
		set {unfortunate...%player%} to true

on damage:
	if {unfortunate...%attacker%} is true:
		chance of 40%
		cancel event
		execute console command "execute as %victim% at @s run playsound minecraft:block.anvil.land master @a ~ ~1 ~ 800 1"

on eat:
	if {unfortunate...%player%} is true:
		chance of 60%
		execute console command "execute as %player% at @s run playsound minecraft:block.anvil.land master @a[distance=0..6] ~ ~1 ~ 800 1"
		cancel event


