#fire gem powers



every 1 second:
	loop all players:
		if loop-player's off hand item is a amethyst shard named "&6&lFire &lgem":
			if {Bliss.Fire.%loop-player%} > 1:
				execute console command "effect give %loop-players% fire_resistance 2 0 true"
			if {Tier2.Stregnth.%loop-player%} is true:
				if {fire.cooldown.%loop-player%} is true:
					send action bar "&6🔺 &aReady!" to loop-player
				if {strength.cooldown.%loop-player%} is true:
					send action bar "&6🔺 &b%{FireMin.%loop-player%}%m %{FireSec.%loop-player%}%s" to loop-player
		if loop-player is holding amethyst shard named "&6&lFire &lgem":
			if {Tier2.Stregnth.%loop-player%} is true:
				if {fire.cooldown.%loop-player%} is  true:
					send action bar "&6🔺 &aReady!" to loop-player
				if {strength.cooldown.%loop-player%} is true:
					send action bar "&6🔺 &b%{FireMin.%loop-player%}%m %{FireSec.%loop-player%}%s" to loop-player
			if {Bliss.Fire.%loop-player%} > 1:
				execute console command "effect give %loop-player% fire_resistance 2 0 true"
		if loop-player is holding prismarine shard named "&6&lFire &lgem":
			if {Bliss.Fire.%loop-player%} > 1:
				execute console command "effect give %loop-player% fire_resistance 2 0 true"
			if {Tier2.Strength.%loop-player%} is true:
				if {fire.cooldown.%loop-player%} is true:
					send action bar "&4♨ &aReady!" to loop-player
				if {fire.cooldown.%loop-player%} is true:
					send action bar "&e⯁ &b%{FireMin.%loop-player%}%m %{FireSec.%loop-player%}%s" to loop-player
			if {Tier2.Stregnth.%loop-player%} is true:
				if {fire.cooldown.%loop-player%} is true:
					if {fire.cooldown2.%loop-player%} is true:
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &aReady! &6🔮  &aReady! &6🧨 &aReady!" to loop-player
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &aReady! &6🔮 &aReady! &6🧨 &b%{FireMin3.%loop-player%}%m %{FireSec3.%loop-player%}%s" to loop-player
				if {fire.cooldown.%loop-player%} is true:
					if {fire.cooldown2.%loop-player%} is true:
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &b%{FireMin2.%loop-player%}%m %{FireSec2.%loop-player%}%s &6🔮 &aReady! &6🧨 &b%{FireMin3.%loop-player%}%m %{FireSec3.%loop-player%}%s" to loop-player
						if {fire.cooldown3.%loop-player%} is not true:
							send action bar "🥾 &b%{FireMin2.%loop-player%}%m %{FireSec2.%loop-player%}%s &6🔮 &aReady! &6🧨 &aReady!" to loop-player
				if {fire.cooldown.%loop-player%} is true:
					if {fire.cooldown2.%loop-player%} is true:
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &b%{FireMin2.%loop-player%}%m %{FireSec2.%loop-player%}%s &6🔮 &b%{FireMin.%loop-player%}%m %{FireSec.%loop-player%}%s 🧨 &b%{StrengthMin3.%loop-player%}%m %{StrengthSec3.%loop-player%}%s" to loop-player
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &b%{FireMin2.%loop-player%}%m %{FireSec2.%loop-player%}%s &6🔮 &b%{FireMin.%loop-player%}%m %{FireSec.%loop-player%}%s 🧨 &aReady!" to loop-player
				if {fire.cooldown.%loop-player%} is true:
					if {fire.cooldown2.%loop-player%} is true:
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &aReady! &6🔮 &b%{FireMin.%loop-player%}%m %{FireSec.%loop-player%}%s 🧨 &aReady!" to loop-player
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &aReady! &6🔮 &b%{FireMin.%loop-player%}%m %{FireSec.%loop-player%}%s 🧨 &b%{FireMin3.%loop-player%}%m %{FireSec3.%loop-player%}%s" to loop-player
		
		if loop-player's off hand item is prismarine shard named "&6&lFire &lgem":
			if {Bliss.Fire.%loop-player%} > 1:
				execute console command "effect give %loop-player% fire_resistance 2 0 true"
			if {Tier2.Stregnth.%loop-player%} is true:
				if {fire.cooldown.%loop-player%} is true:
					if {fire.cooldown2.%loop-player%} is true:
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &aReady! &6🔮  &aReady! &6🧨 &aReady!" to loop-player
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &aReady! &6🔮 &aReady! &6🧨 &b%{FireMin3.%loop-player%}%m %{FireSec3.%loop-player%}%s" to loop-player
				if {fire.cooldown.%loop-player%} is true:
					if {fire.cooldown2.%loop-player%} is true:
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &b%{FireMin2.%loop-player%}%m %{FireSec2.%loop-player%}%s &4♨ &aReady! &6🧨 &b%{FireMin3.%loop-player%}%m %{FireSec3.%loop-player%}%s" to loop-player
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &b%{FireMin2.%loop-player%}%m %{FireSec2.%loop-player%}%s &4♨ &aReady! &6🧨 &aReady!" to loop-player
				if {fire.cooldown.%loop-player%} is true:
					if {fire.cooldown2.%loop-player%} is true:
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &b%{FireMin2.%loop-player%}%m %{FireSec2.%loop-player%}%s &6🔮 &b%{FireMin.%loop-player%}%m %{FireSec.%loop-player%}%s 🧨 %{FireSec3.%loop-player%}%s" to loop-player
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &b%{FireMin2.%loop-player%}%m %{FireSec2.%loop-player%}%s &6🔮 &b%{FireMin.%loop-player%}%m %{FireSec.%loop-player%}%s 🧨 &aReady!" to loop-player
				if {fire.cooldown.%loop-player%} is true:
					if {fire.cooldown2.%loop-player%} is true:
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &aReady! &6🔮 &b%{FireMin.%loop-player%}%m %{FireSec.%loop-player%}%s 🧨 &aReady!" to loop-player
						if {fire.cooldown3.%loop-player%} is true:
							send action bar "🥾 &aReady! &6🔮 &b%{FireMin.%loop-player%}%m %{FireSec.%loop-player%}%s 🧨 %{FireSec3.%loop-player%}%s" to loop-player


		if loop-player has a prismarine shard named "&6&lFire &lgem":
			remove 1 from {FireSec.%loop-player%}
			remove 1 from {FireSec2.%loop-player%}
			remove 1 from {FireSec3.%loop-player%}
			if {FireSec.%loop-player%} is -1:
				remove 1 from {FireMin.%loop-player%}
				set {FireSec.%loop-player%} to 59
				if {FireMin.%loop-player%} is -1:
					set {fire.cooldown.%loop-player%} to false
			if {FireSec2.%loop-player%} is -1:
				remove 1 from {FireMin2.%loop-player%}
				set {FireSec2.%loop-player%} to 59
				if {FireMin2.%loop-player%} is -1:
					set {Fire.cooldown2.%loop-player%} to false
			if {FireSec3.%loop-player%} < 0:
				remove 1 from {FireMin3.%loop-player%}
				set {FireSec3.%loop-player%} to 59
				if {FireMin3.%loop-player%} is -1:
					set {fire.cooldown3.%loop-player%} to false
		if loop-player has a amethyst shard named "&6&lFire &lgem":
			remove 1 from {FireSec.%loop-player%}
			remove 1 from {FireSec2.%loop-player%}
			remove 1 from {FireSec3.%loop-player%}
			if {FireSec.%loop-player%} is -1:
				remove 1 from {FireMin.%loop-player%}
				set {FireSec.%loop-player%} to 59
				if {FireMin.%loop-player%} is -1:
					set {fire.cooldown.%loop-player%} to false

on sneak toggle:
	if {Tag..%player%} is 0:
		if player's off hand item is prismarine shard named "&6&lFire &lgem":
			if {Tier2.Stregnth.%player%} is true:
				if {fire.cooldown2.%player%} is not true:
					if player's held item is a any sword:
						execute console command "enchant %player% fire_aspect 2"
						send "&aEnchanting Tool with &eFire aspect &42"
						set {FireMin2.%player%} to 1
						set {FireSec2.%player%} to 59
						set {fire.cooldown2.%player%} to true
		if player's off hand item is amethyst shard named "&6&lFire &lgem":
			if {Tier2.Stregnth.%player%} is not true:
				if {fire.cooldown2.%player%} is not true:
					if player's held item is a any sword:
						execute console command "enchant %player% fire_aspect 1"
						send "&aEnchanting Tool with &eFire aspect &41"
						set {FireMin.%player%} to 1
						set {FireSec.%player%} to 59
						set {fire.cooldown.%player%} to false

on drop prismarine shard:
	if event-item is prismarine shard named "&6&lFire &lgem":
		cancel event
on drop amethyst shard:
	if event-item is amethyst shard named "&6&lFire &lgem":
		cancel event
		
every 0.1 tick:
	loop all players:
		if {fireball.%loop-player%} > 0:
			execute console command "execute as %loop-player% at @s run execute as @e[type=armor_stand,tag=5%loop-player%] run tp ~ ~2.5 ~"
			execute console command "execute as %loop-player% at @s run particle dust 1 0.42 0 1.4 ~ ~.2 ~ 0.2 0.2 0.2 0 5 force @a"

on right click:
	if player's held item is a prismarine shard named "&6&lFire &lgem":
		if clicked block is not air:
			if block above clicked block is air:
				set block above clicked block to soul campfire
				send "&9Cozy campfire"
				execute console command "tag add %player% TrustedBy%player%"
				wait 15 seconds
				set block above clicked block to air

every 1 second:
	loop all players:
		if blocks in radius 4 of loop-player contains soul campfire:
			execute console command "execute as %loop-player% at @s run effect give @s saturation 1 0 true"
			execute console command "execute as %loop-player% at @s run effect give @s regeneration 1 0 true"


on left click:
	if player's held item is a prismarine shard named "&6&lFire &lgem":
		if {Tag..%player%} is 0:
			if {fire.cooldown3.%player%} is not true: 
				wait 1 tick
				send "&6🔮 &bYou are Charging a &6Fireball"
				execute console command "execute as %player% at @s run summon armor_stand ~ ~ ~ {Tags:[""5%player%""],Invisible:1b}"
				execute console command "execute as %player% at @s run item replace entity @e[type=armor_stand,distance=0..2] armor.head with fire_charge"
				make last spawned entity ride player
				if {Bliss.Fire.%player%} > 4:
					set {FireMin3.%player%} to 0
					set {FireSec3.%player%} to 45
					set {Fire.cooldown3.%player%} to true
				if {Bliss.Fire.%player%} is 3:
					set {FireMin3.%player%} to 1
					set {FireSec3.%player%} to 1
					set {Fire.cooldown3.%player%} to true
				if {Bliss.Fire.%player%} < 3:
					set {FireMin3.%player%} to 1
					set {FireSec3.%player%} to 25
					set {Fire.cooldown3.%player%} to true
				set {fireball.%player%} to 1
				send "&610%% Charged" to player
				wait 3 second
				if {fireball.%player%} is 1:
					set {fireball.%player%} to 2
					send "&620%% Charged" to player
				wait 3 second
				if {fireball.%player%} is 2:
					set {fireball.%player%} to 3
					send "&630%% Charged" to player
				wait 3 second
				if {fireball.%player%} is 3:
					set {fireball.%player%} to 4
					send "&640%% Charged" to player
				wait 3 second
				if {fireball.%player%} is 4:
					set {fireball.%player%} to 5
					send "&650%% Charge" to player
				wait 3 second
				if {fireball.%player%} is 5:
					set {fireball.%player%} to 6
					send "&660%% Charge" to player
				wait 3 second
				if {fireball.%player%} is 6:
					set {fireball.%player%} to 7
					send "&670%% Charge" to player
				wait 3 second
				if {fireball.%player%} is 7:
					set {fireball.%player%} to 8
					send "&680%% Charge" to player
				wait 3 second
				if {fireball.%player%} is 8:
					set {fireball.%player%} to 9
					send "&690%% Charge" to player
				wait 3 second
				if {fireball.%player%} is 9:
					set {fireball.%player%} to 10
					send "&6100%% Charge" to player
			
on damage:
	if damage cause is fireball:
		chance of 80%
		push victim up at speed 2.5
		push victim backwards at speed 1.2

every 1 tick:
	loop all players:
		if loop-player's offhand item is a prismarine shard named "&6&lFire &lgem":
			if loop-player has raw iron:
				remove 1 raw iron from loop-player
				give loop-player 1 iron ingot
			if loop-player has raw gold:
				remove 1 raw gold from loop-player
				give loop-player 1 gold ingot
			if loop-player has mutton:
				remove 1 mutton from loop-player
				give loop-player 1 cooked mutton
			if loop-player has cobblestone:
				remove 1 cobblestone from loop-player
				give loop-player 1 stone
		if loop-player's offhand item is a amethyst shard named "&6&lFire &lgem":
			if loop-player has raw iron:
				remove 1 raw iron from loop-player
				give loop-player 1 iron ingot
			if loop-player has raw gold:
				remove 1 raw gold from loop-player
				give loop-player 1 gold ingot
			if loop-player has mutton:
				remove 1 mutton from loop-player
				give loop-player 1 cooked mutton
			if loop-player has cobblestone:
				remove 1 cobblestone from loop-player
				give loop-player 1 stone
				
on damage:
	if {zerodamage..%victim%} is true:
		cancel event

on left click:
	if player's held item is a prismarine shard named "&6&lFire &lgem":
		if {Tag..%player%} is 0:
			if {fireball.%player%} is 1:
				set {fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:2}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {fireball.%player%} is 2:
				set {fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:2}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {fireball.%player%} is 3:
				set {fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:2.4}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {fireball.%player%} is 4:
				set {fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:2.7}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {fireball.%player%} is 5:
				set {fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:3.4}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {fireball.%player%} is 6:
				set {fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:3.8}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {fireball.%player%} is 7:
				set {fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:3.8}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {fireball.%player%} is 8:
				set {fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:4.4}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {fireball.%player%} is 9:
				set {fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:5.2}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false
			if {fireball.%player%} is 10:
				set {fireball.%player%} to 0
				execute console command "execute as %player% at @s run summon fireball ~ ~1 ~ {ExplosionPower:5.8}"
				execute console command "execute as %player% at @s run kill @e[type=armor_stand,distance=0..4]"
				set {zerodamage..%player%} to true
				wait 4 second
				set {zerodamage..%player%} to false