on death of player:
	if attacker's off hand item is a prismarine shard named "&d&lLife &lgem":
		add 1 to {Bliss.Life.%attacker%} 
		if {Bliss.Life.%attacker%} is 1:
			set attacker's off hand item to prismarine shard with custom model data 96 named "&d&lLife &lgem" with lore "&8Broken Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
		if {Bliss.Life.%attacker%} is 2:
			set attacker's off hand item to prismarine shard with custom model data 84 named "&d&lLife &lgem" with lore "&4Ruined Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
		if {Bliss.Life.%attacker%} is 3:
			set attacker's off hand item to prismarine shard with custom model data 64 named "&d&lLife &lgem" with lore "&eDamaged Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
		if {Bliss.Life.%attacker%} is 4:
			set attacker's off hand item to prismarine shard with custom model data 44 named "&d&lLife &lgem" with lore "&aCracked Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
		if {Bliss.Life.%attacker%} is 5:
			set attacker's off hand item to prismarine shard with custom model data 24 named "&d&lLife &lgem" with lore "&aScratched Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
		if {Bliss.Life.%attacker%} is 6:
			set attacker's off hand item to prismarine shard with custom model data 4 named "&d&lLife &lgem" with lore "&bPristine Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
		if {Bliss.Life.%attacker%} is 7:
			set attacker's off hand item to prismarine shard with custom model data 4 named "&d&lLife &lgem" with lore "&bPristine + 1 Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
		if {Bliss.Life.%attacker%} is 8:
			set attacker's off hand item to prismarine shard with custom model data 4 named "&d&lLife &lgem" with lore "&bPristine + 2 Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
		if {Bliss.Life.%attacker%} is 9:
			set attacker's off hand item to prismarine shard with custom model data 4 named "&d&lLife &lgem" with lore "&bPristine + 3 Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
		if {Bliss.Life.%attacker%} is 10:
			set attacker's off hand item to prismarine shard with custom model data 4 named "&d&lLife &lgem" with lore "&bPristine + 4 Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
		if {Bliss.Life.%attacker%} > 10:
			set {item} to prismarine shard with custom model data 4 named "&d&lLife &lgem" with lore "&bPristine + 5 Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
			set attacker's off hand item to {item}
			enchant {item} with mending 1
