#Life Powers






every 1 tick:
	loop all players:
		set {_uuid} to uuid of loop-player
		
		if loop-player's off hand item or loop-player's held item is a amethyst shard named "&d&lLife &lgem":
			send action bar "&f🔺%{Life.Power2.HeartDrainer.Display.%{_uuid}%}%" to loop-player



		if loop-player's off hand item is prismarine shard named "&d&lLife &lgem":

			send action bar "%{Life.Power3.Breezy.Display.%{_uuid}%}% &f🔮%{Life.Power2.HeartDrainer.Display.%{_uuid}%}% &f%{Life.Power1.CircleOfLfe.Display.%{_uuid}%}%" to loop-player
		
		
		if loop-player's held item or loop-player's held item is a amethyst shard named "&d&lLife &lgem":
			send action bar "&f🔺%{Life.Power2.HeartDrainer.Display.%{_uuid}%}%" to loop-player



		if loop-player's held item is prismarine shard named "&d&lLife &lgem":
			send action bar "%{Life.Power3.Breezy.Display.%{_uuid}%}% &f🔮%{Life.Power2.HeartDrainer.Display.%{_uuid}%}% &f%{Life.Power1.CircleOfLfe.Display.%{_uuid}%}%" to loop-player






every 1 second:
	loop all players:
		if loop-player has a prismarine shard or amethyst shard named "&d&lLife &lgem":
			set {_uuid} to uuid of loop-player

			#Breezy
			if {Life.Power3.Breezy.Cooldown.%{_uuid}%} is true:
				if {Life.Power3.Breezy.Minute.%{_uuid}%} is 0:
					set {Life.Power3.Breezy.Display.%{_uuid}%} to "&f☁ &b%{Life.Power3.Breezy.Second.%{_uuid}%}%s"

				else:
					set {Life.Power3.Breezy.Display.%{_uuid}%} to "&f☁ &b%{Life.Power3.Breezy.Minute.%{_uuid}%}%m %{Life.Power3.Breezy.Second.%{_uuid}%}%s"		
			if {Life.Power3.Breezy.Second.%{_uuid}%} is not set:
				set {Life.Power3.Breezy.Second.%{_uuid}%} to 0
				set {Life.Power3.Breezy.Minute.%{_uuid}%} to 0
				set {Life.Power3.Breezy.Cooldown.%{_uuid}%} to true

			if {Life.Power3.Breezy.Display.%{_uuid}%} is not set:
				set {Life.Power3.Breezy.Display.%{_uuid}%} to "&f☁ &b%{Life.Power3.Breezy.Minute.%{_uuid}%}%m %{Life.Power3.Breezy.Second.%{_uuid}%}%s"
				
		
			if {Life.Power3.Breezy.Cooldown.%{_uuid}%} is true:
				if {Life.Power3.Breezy.Minute.%{_uuid}%} is 0:
					set {Life.Power3.Breezy.Display.%{_uuid}%} to "&f☁ &b%{Life.Power3.Breezy.Second.%{_uuid}%}%s"

				else:
					set {Life.Power3.Breezy.Display.%{_uuid}%} to "&f☁ &b%{Life.Power3.Breezy.Minute.%{_uuid}%}%m %{Life.Power3.Breezy.Second.%{_uuid}%}%s"

			if {Life.Power3.Breezy.Cooldown.%{_uuid}%} is true:
				remove 1 from {Life.Power3.Breezy.Second.%{_uuid}%}



			if {Life.Power3.Breezy.Second.%{_uuid}%} is -1:
				remove 1 from {Life.Power3.Breezy.Minute.%{_uuid}%}
				set {Life.Power3.Breezy.Second.%{_uuid}%} to 59
                
			if {Life.Power3.Breezy.Minute.%{_uuid}%} is -1:
				set {Life.Power3.Breezy.Cooldown.%{_uuid}%} to false
				set {Life.Power3.Breezy.Display.%{_uuid}%} to "&f☁ &aReady!"


			#HeartDrainer

			if {Life.Power2.HeartDrainer.Second.%{_uuid}%} is not set:
				set {Life.Power2.HeartDrainer.Second.%{_uuid}%} to 0
				set {Life.Power2.HeartDrainer.Minute.%{_uuid}%} to 0
				set {Life.Power2.HeartDrainer.Cooldown.%{_uuid}%} to true

			if {Life.Power2.HeartDrainer.Minute.%{_uuid}%} is not set:
				set {Life.Power2.HeartDrainer.Second.%{_uuid}%} to 0
				set {Life.Power2.HeartDrainer.Minute.%{_uuid}%} to 0
				set {Life.Power2.HeartDrainer.Cooldown.%{_uuid}%} to true


			if {Life.Power2.HeartDrainer.Cooldown.%{_uuid}%} is not set:
				set {Life.Power2.HeartDrainer.Second.%{_uuid}%} to 0
				set {Life.Power2.HeartDrainer.Minute.%{_uuid}%} to 0
				set {Life.Power2.HeartDrainer.Cooldown.%{_uuid}%} to true	
				set {Life.Power2.HeartDrainer.Display.%{_uuid}%} to " &b%{Life.Power2.HeartDrainer.Minute.%{_uuid}%}%m %{Life.Power2.HeartDrainer.Second.%{_uuid}%}%s"

			if {Life.Power2.HeartDrainer.Display.%{_uuid}%} is not set:
				set {Life.Power2.HeartDrainer.Second.%{_uuid}%} to 0
				set {Life.Power2.HeartDrainer.Minute.%{_uuid}%} to 0
				set {Life.Power2.HeartDrainer.Cooldown.%{_uuid}%} to true	

			if {Life.Power2.HeartDrainer.Cooldown.%{_uuid}%} is true:
				set {Life.Power2.HeartDrainer.Display.%{_uuid}%} to "&b %{Life.Power2.HeartDrainer.Minute.%{_uuid}%}%m %{Life.Power2.HeartDrainer.Second.%{_uuid}%}%s"

			if {Life.Power2.HeartDrainer.Display.%{_uuid}%} is not set:
				set {Life.Power2.HeartDrainer.Display.%{_uuid}%} to " &b %{Life.Power2.HeartDrainer.Minute.%{_uuid}%}%m %{Life.Power2.HeartDrainer.Second.%{_uuid}%}%s"

			if {Life.Power2.HeartDrainer.Cooldown.%{_uuid}%} is true:
				if {Life.Power2.HeartDrainer.Minute.%{_uuid}%} is 0:
					set {Life.Power2.HeartDrainer.Display.%{_uuid}%} to "&b %{Life.Power2.HeartDrainer.Second.%{_uuid}%}%s"

				else:
					set {Life.Power2.HeartDrainer.Display.%{_uuid}%} to "&b %{Life.Power2.HeartDrainer.Minute.%{_uuid}%}%m %{Life.Power2.HeartDrainer.Second.%{_uuid}%}%s"

			if {Life.Power2.HeartDrainer.Cooldown.%{_uuid}%} is true:
				remove 1 from {Life.Power2.HeartDrainer.Second.%{_uuid}%}


			
			if {Life.Power2.HeartDrainer.Second.%{_uuid}%} is -1:
				remove 1 from {Life.Power2.HeartDrainer.Minute.%{_uuid}%}
				set {Life.Power2.HeartDrainer.Second.%{_uuid}%} to 59
                
			if {Life.Power2.HeartDrainer.Minute.%{_uuid}%} is -1:
				set {Life.Power2.HeartDrainer.Cooldown.%{_uuid}%} to false
				set {Life.Power2.HeartDrainer.Display.%{_uuid}%} to " &aReady!"



			#CircleOfLfe





			if {Life.Power1.CircleOfLfe.Cooldown.%{_uuid}%} is true:
				remove 1 from {Life.Power1.CircleOfLfe.Second.%{_uuid}%}


			
			if {Life.Power1.CircleOfLfe.Second.%{_uuid}%} is -1:
				remove 1 from {Life.Power1.CircleOfLfe.Minute.%{_uuid}%}
				set {Life.Power1.CircleOfLfe.Second.%{_uuid}%} to 59


			if {Life.Power1.CircleOfLfe.Cooldown.%{_uuid}%} is true:
				if {Life.Power1.CircleOfLfe.Minute.%{_uuid}%} is 0:
					set {Life.Power1.CircleOfLfe.Display.%{_uuid}%} to "&f⏫ &b%{Life.Power1.CircleOfLfe.Second.%{_uuid}%}%s"

				else:
					set {Life.Power1.CircleOfLfe.Display.%{_uuid}%} to "&f⏫ &b%{Life.Power1.CircleOfLfe.Minute.%{_uuid}%}%m %{Life.Power1.CircleOfLfe.Second.%{_uuid}%}%s"


			if {Life.Power1.CircleOfLfe.Second.%{_uuid}%} is not set:
				set {Life.Power1.CircleOfLfe.Second.%{_uuid}%} to 0
				set {Life.Power1.CircleOfLfe.Minute.%{_uuid}%} to 0

			if {Life.Power1.CircleOfLfe.Cooldown.%{_uuid}%} is not set:
				set {Life.Power1.CircleOfLfe.Second.%{_uuid}%} to 0
				set {Life.Power1.CircleOfLfe.Minute.%{_uuid}%} to 0
				set {Life.Power1.CircleOfLfe.Cooldown.%{_uuid}%} to true	

			if {Life.Power1.CircleOfLfe.Display.%{_uuid}%} is not set:
				set {Life.Power1.CircleOfLfe.Second.%{_uuid}%} to 0
				set {Life.Power1.CircleOfLfe.Minute.%{_uuid}%} to 0
				set {Life.Power1.CircleOfLfe.Cooldown.%{_uuid}%} to true	


			if {Life.Power1.CircleOfLfe.Display.%{_uuid}%} is not set:
				set {Life.Power1.CircleOfLfe.Display.%{_uuid}%} to "&f⏫ &b%{Life.Power1.CircleOfLfe.Minute.%{_uuid}%}%m %{Life.Power1.CircleOfLfe.Second.%{_uuid}%}%s"



			if {Life.Power1.CircleOfLfe.Minute.%{_uuid}%} is -1:
				set {Life.Power1.CircleOfLfe.Cooldown.%{_uuid}%} to false
				set {Life.Power1.CircleOfLfe.Display.%{_uuid}%} to "&f⏫ &aReady!"


on eat:
	apply saturation 2 without particles to player for 1 tick
	
command /trust [<text>] [<offlineplayer>] [<integer>]:
	trigger:
		if arg-1 is "add":
			if arg-2 is set:
				if arg-3 is 1:
					set {Trusted.%player%.1} to arg-2
					send "&c%player% has added you as &6Trusted player" to arg-2
					execute console command "tag %arg-2% add TrustedBy%player%"
				if arg-3 is 2:
					set {Trusted.%player%.2} to arg-2
					send "&c%player% has added you as &6Trusted player" to arg-2
					execute console command "tag %arg-2% add TrustedBy%player%"
				if arg-3 is 3:
					set {Trusted.%player%.3} to arg-2
					send "&c%player% has added you as &6Trusted player" to arg-2
					execute console command "tag %arg-2% add TrustedBy%player%"
		if arg-1 is "remove":
			if arg-2 is set:
				if arg-3 is 1:
					set {Trusted.%player%.1} to false
					send "&c%arg-1% is removed from trust list" to arg-2
					execute console command "tag %arg-2% remove TrustedBy%player%"
				if arg-3 is 2:
					set {Trusted.%player%.1} to false
					send "&c%arg-1% is removed from trust list" to arg-2
					execute console command "tag %arg-2% remove TrustedBy%player%"
				if arg-3 is 3:
					set {Trusted.%player%.1} to false
					send "&c%arg-1% is removed from trust list" to arg-2
					execute console command "tag %arg-2% remove TrustedBy%player%"
				
on tab complete for "/trust":
    set tab completions for position 1 to "add" and "remove"
		


on drop prismarine shard:
	if event-item is prismarine shard named "&d&lLife &lgem":
		cancel event
on drop amethyst shard:
	if event-item is amethyst shard named "&d&lLife &lgem":
		cancel event		


on right click on wheat plant:
	if player's off hand item is a amethyst shard named "&d&lLife &lgem":
		set event-block to stage 3 wheat plant
		chance of 40%
		set event-block to stage 4 wheat plant
		chance of 20%
		set event-block to fully grown wheat plant
	if player's off hand item is a prismarine shard named "&d&lLife &lgem":
		set event-block to stage 3 wheat plant
		chance of 40%
		set event-block to stage 4 wheat plant
		chance of 20%
		set event-block to fully grown wheat plant
on right click on stage 2 wheat plant:
	if player's off hand item is a amethyst shard named "&d&lLife &lgem":
		set event-block to stage 3 wheat plant
		chance of 40%
		set event-block to stage 4 wheat plant
		chance of 20%
		set event-block to fully grown wheat plant
	if player's off hand item is a prismarine shard named "&d&lLife &lgem":
		set event-block to stage 3 wheat plant
		chance of 40%
		set event-block to stage 4 wheat plant
		chance of 20%
		set event-block to fully grown wheat plant
on right click on stage 3 wheat plant:
	if player's off hand item is a amethyst shard named "&d&lLife &lgem":
		chance of 20%
		set event-block to stage 4 wheat plant
		chance of 20%
		set event-block to fully grown wheat plant
	if player's off hand item is a prismarine shard named "&d&lLife &lgem":
		chance of 40%
		set event-block to stage 4 wheat plant
		chance of 20%
		set event-block to fully grown wheat plant
on right click on stage 4 wheat plant:
	if player's off hand item is a amethyst shard named "&d&lLife &lgem":
		chance of 20%
		set event-block to fully grown wheat plant
	if player's off hand item is a prismarine shard named "&d&lLife &lgem":
		chance of 20%
		set event-block to fully grown wheat plant
on eat golden apple:
	if player's off hand item is a amethyst shard named "&d&lLife &lgem":
		apply absorption 2 to player for 1 minute
	if player's off hand item is a prismarine shard named "&d&lLife &lgem":
		remove absorption from player
		apply absorption 2 to player for 1 minute


every 15 tick:
	loop all players:
		if loop-player has prismarine shard named "&d&lLife &lgem":
			execute console command "execute as @e[tag=Life] at @s run function particles:life"
	
every 1 tick:
	loop all players:
		if loop-player has prismarine shard named "&d&lLife &lgem":
			execute console command "execute as @e[tag=Life] at @s run function particles:life"
			execute console command "execute as @e[tag=Life] at @s run execute as @a[distance=1.5..6,tag=!TrustedBy%loop-player%] at @s run attribute @s minecraft:generic.max_health base set %{Healt....%loop-player%}%"
			execute console command "execute as @e[tag=Life] at @s run execute as @a[distance=7..99] at @s run attribute @s minecraft:generic.max_health base set 20"

on damage:
	if attacker's held item is a prismarine shard named "&d&lLife &lgem":
		if {life.cooldown3.%attacker%} is not true:
			if {Tag..%attacker%} is 0:
				if {Bliss.Life.%attacker%} > 4:
					set {LifeSec3.%attacker%} to 30
					set {LifeMin3.%attacker%} to 2
					set {life.cooldown3.%attacker%} to true
				if {Bliss.Life.%attacker%} is 3:
					set {LifeSec3.%attacker%} to 1
					set {LifeMin3.%attacker%} to 3
					set {life.cooldown3.%attacker%} to true
				if {Bliss.Life.%attacker%} < 3:
					set {LifeSec3.%attacker%} to 35
					set {LifeMin3.%attacker%} to 3
					set {life.cooldown3.%attacker%} to true
				set {HP..%victim%} to a random integer between 1 and 4
				if {HP..%victim%} is 1:
					send "&dDecreased %victim%'s hp by 5%%" to attacker
					send "&c%attacker% decreased &dyour hp by 5%%" to victim
				if {HP..%victim%} is 2:
					send "&dDecreased %victim%'s hp by 10%%" to attacker
					send "&c%attacker% decreased &dyour hp by 10%%" to victim
				if {HP..%victim%} is 3:
					send "&dDecreased %victim%'s hp by 15%%" to attacker
					send "&c%attacker% decreased &dyour hp by 15%%" to victim
				if {HP..%victim%} is 4:
					send "&dDecreased %victim%'s hp by 20%%" to attacker
					send "&c%attacker% decreased &dyour hp by 20%%" to victim
					remove 2 from victim's max health
				wait 40 seconds
				set victim's max health to 10

on left click:
	if player's held item is a prismarine shard named "&d&lLife &lgem":
		set {_uuid} to uuid of player
		if {Life.Power1.CircleOfLfe.Cooldown.%{_uuid}%} is false:
			set {_Lifeholder} to player
			execute player command "/lifecircle 1"
			execute player command "/lifecircle 2"
			execute player command "/lifecircle 3"
			execute player command "/lifecircle 4"
			execute player command "/lifecircle 5"
			execute player command "/lifecircle 6"
			execute player command "/lifecircle 7"
			execute player command "/lifecircle 8"
			loop all players within 8 blocks of the player:
				if loop-player is not {_Lifeholder}:
				
					if name of loop-player contains "%{Trusted.%{_Lifeholder}%.1}%":
						add 4 to loop-player's max health
					else:
						remove 4 from loop-player's max health

					if name of loop-player contains "%{Trusted.%{_Lifeholder}%.2}%":
						add 4 to loop-player's max health
					else:
						remove 4 from loop-player's max health

					if name of loop-player contains "%{Trusted.%{_Lifeholder}%.3}%":
						add 4 to loop-player's max health
					else:
						remove 4 from loop-player's max health

					if {Bliss.Life.%{_Lifeholder}%} > 4:
						set {Life.Power1.CircleOfLfe.Second.%{_uuid}%} to 30
						set {Life.Power1.CircleOfLfe.Minute.%{_uuid}%} to 2
						set {Life.Power1.CircleOfLfe.Cooldown.%{_uuid}%} to true
					if {Bliss.Life.%{_Lifeholder}%} is 3:
						set {Life.Power1.CircleOfLfe.Second.%{_uuid}%} to 1
						set {Life.Power1.CircleOfLfe.Minute.%{_uuid}%} to 3
						set {Life.Power1.CircleOfLfe.Cooldown.%{_uuid}%} to true
					if {Bliss.Life.%{_Lifeholder}%} < 3:
						set {Life.Power1.CircleOfLfe.Second.%{_uuid}%} to 35
						set {Life.Power1.CircleOfLfe.Minute.%{_uuid}%} to 3

					set {Life.Power1.CircleOfLfe.Cooldown.%{_uuid}%} to true
					wait 10 seconds
					set loop-player's max health to 10
					set {_Lifeholder}'s max health to 10

on right click on entity:
	if player's held item is a prismarine shard named "&d&lLife &lgem":
		if {life.cooldown2.%player%} is not true:
			if {Tag..%player%} is 0:
				set {LifeSec2.%player%} to 59
				set {LifeMin2.%player%} to 3
				set {life.cooldown2.%player%} to true
				set {HP..%event-entity%} to a random integer between 7 and 8
				execute console command "tag %player% add Life"
				if {HP..%event-entity%} is 1:
					set {Healt....%player%} to 19
					send "&dDecreased %event-entity%'s hp by 5%%" to player
					send "&c%player% decreased &dyour hp by 5%%"
				if {HP..%event-entity%} is 2:
					set {Healt....%player%} to 18
					send "&dDecreased %event-entity%'s hp by 10%%" to player
					send "&c%player% decreased &dyour hp by 10%%"
				if {HP..%event-entity%} is 3:
					set {Healt....%player%} to 17
					send "&dDecreased %event-entity%'s hp by 15%%" to player
					send "&c%player% decreased &dyour hp by 15%%"
				if {HP..%event-entity%} is 4:
					set {Healt....%player%} to 16
					send "&dDecreased %event-entity%'s hp by 20%%" to player
					send "&c%player% decreased &dyour hp by 20%%"
				if {HP..%event-entity%} is 5:
					set {Healt....%player%} to 15
					send "&dDecreased %event-entity%'s hp by 25%%" to player
					send "&c%player% decreased &dyour hp by 25%%"
				if {HP..%event-entity%} is 6:
					set {Healt....%player%} to 14
					send "&dDecreased %event-entity%'s hp by 30%%" to player
					send "&c%player% decreased &dyour hp by 30%%"
				if {HP..%event-entity%} is 7:
					set {Healt....%player%} to 13
					send "&dDecreased %event-entity%'s hp by 35%%" to player
					send "&c%player% decreased &dyour hp by 35%%"
				if {HP..%event-entity%} is 8:
					set {Healt....%player%} to 12
					send "&dDecreased %event-entity%'s hp by 40%%" to player
					send "&c%player% decreased &dyour hp by 40%%"
				wait 60 seconds
				execute console command "execute as @a at @s run attribute @s minecraft:generic.max_health base set 20"
				set {Healt....%player%} to false
				execute console command "tag %player% remove Life"






