on death of player:
	wait 1 tick
	if {Bliss.Strength.%attacker%} is 0:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &fN/A" to attacker
	if {Bliss.Strength.%attacker%} is 1:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &7Broken" to attacker
	if {Bliss.Strength.%attacker%} is 2:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &4Ruined" to attacker
	if {Bliss.Strength.%attacker%} is 3:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &eDamaged" to attacker
	if {Bliss.Strength.%attacker%} is 4:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &aCracked" to attacker
	if {Bliss.Strength.%attacker%} is 5:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &aScratched" to attacker
	if {Bliss.Strength.%attacker%} is 6:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine" to attacker
	if {Bliss.Strength.%attacker%} is 7:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine + 1" to attacker
	if {Bliss.Strength.%attacker%} is 8:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine + 2" to attacker
	if {Bliss.Strength.%attacker%} is 9:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine + 3" to attacker
	if {Bliss.Strength.%attacker%} is 10:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine + 4" to attacker
	if {Bliss.Strength.%attacker%} > 10:
		send "&bYou &agained &benergy &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine + 5" to attacker
		

	if {Bliss.Strength.%victim%} is 0:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &fN/A" to victim
	if {Bliss.Strength.%victim%} is 1:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &7Broken" to victim
	if {Bliss.Strength.%victim%} is 2:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &4Ruined" to victim
	if {Bliss.Strength.%victim%} is 3:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &eDamaged" to victim
	if {Bliss.Strength.%victim%} is 4:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &aCracked" to victim
	if {Bliss.Strength.%victim%} is 5:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &aScratched" to victim
	if {Bliss.Strength.%victim%} is 6:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine" to victim
	if {Bliss.Strength.%victim%} is 7:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine + 1" to victim
	if {Bliss.Strength.%victim%} is 8:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine + 2" to victim
	if {Bliss.Strength.%victim%} is 9:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine + 3" to victim
	if {Bliss.Strength.%victim%} is 10:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine + 4" to victim
	if {Bliss.Strength.%victim%} > 10:
		send "&bYou lost &cenergy. &byour &4&lsᴛʀᴇɴɢᴛʜ &bgem is now at &bPristine + 5" to victim