#Gem Strength Powers

every 1 tick:
	loop all players:
		set {_uuid} to uuid of loop-player
		if loop-player's off hand item or loop-player's held item is a amethyst shard named "&4&lStrength &e&lgem":
			
			send action bar "&c🔺 %{Strength.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player
			


		if loop-player's off hand item is prismarine shard named "&4&lStrength &e&lgem":

			send action bar "%{Strength.Power1.Frailer.Display.%{_uuid}%}% &4🔮%{Strength.Power2.Enchanting.Display.%{_uuid}%}% %{Strength.Power3.Chad.Display.%{_uuid}%}%" to loop-player
		
		if loop-player's held item or loop-player's held item is a amethyst shard named "&4&lStrength &e&lgem":

			send action bar "&c🔺 %{Strength.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player



		if loop-player's held item is prismarine shard named "&4&lStrength &e&lgem":

			send action bar "%{Strength.Power1.Frailer.Display.%{_uuid}%}% &4🔮%{Strength.Power2.Enchanting.Display.%{_uuid}%}% %{Strength.Power3.Chad.Display.%{_uuid}%}%" to loop-player



every 1 second:
	loop all players:
		set {_uuid} to uuid of loop-player
		if loop-player has a prismarine shard or amethyst shard named "&4&lStrength &e&lgem":


			#Chad
			if {Strength.Power3.Chad.Second.%{_uuid}%} is not set:
				set {Strength.Power3.Chad.Second.%{_uuid}%} to 1
				set {Strength.Power3.Chad.Minute.%{_uuid}%} to 59
				set {Strength.Power3.Chad.Cooldown.%{_uuid}%} to true

			if {Strength.Power3.Chad.Minute.%{_uuid}%} is not set:
				set {Strength.Power3.Chad.Second.%{_uuid}%} to 1
				set {Strength.Power3.Chad.Minute.%{_uuid}%} to 59
				set {Strength.Power3.Chad.Cooldown.%{_uuid}%} to true

			if {Strength.Power3.Chad.Cooldown.%{_uuid}%} is not set:
				set {Strength.Power3.Chad.Second.%{_uuid}%} to 1
				set {Strength.Power3.Chad.Minute.%{_uuid}%} to 59
				set {Strength.Power3.Chad.Cooldown.%{_uuid}%} to true
		
			if {Strength.Power3.Chad.Cooldown.%{_uuid}%} is true:
				set {Strength.Power3.Chad.Display.%{_uuid}%} to "&c⚔ &b%{Strength.Power3.Chad.Minute.%{_uuid}%}%m %{Strength.Power3.Chad.Second.%{_uuid}%}%s"
			
			if {Strength.Power3.Chad.Cooldown.%{_uuid}%} is true:
				remove 1 from {Strength.Power3.Chad.Second.%{_uuid}%}


			
			if {Strength.Power3.Chad.Second.%{_uuid}%} is -1:
				remove 1 from {Strength.Power3.Chad.Minute.%{_uuid}%}
				set {Strength.Power3.Chad.Second.%{_uuid}%} to 59
                
			if {Strength.Power3.Chad.Minute.%{_uuid}%} is -1:
				set {Strength.Power3.Chad.Cooldown.%{_uuid}%} to false
				set {Strength.Power3.Chad.Second.%{_uuid}%} to 59
				set {Strength.Power3.Chad.Minute.%{_uuid}%} to 1
				set {Strength.Power3.Chad.Display.%{_uuid}%} to "&c⚔ &aReady!"


			#Enchanting

			if {Strength.Power2.Enchanting.Second.%{_uuid}%} is not set:
				set {Strength.Power2.Enchanting.Second.%{_uuid}%} to 59
				set {Strength.Power2.Enchanting.Minute.%{_uuid}%} to 1
				set {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} to true

			if {Strength.Power2.Enchanting.Minute.%{_uuid}%} is not set:
				set {Strength.Power2.Enchanting.Second.%{_uuid}%} to 59
				set {Strength.Power2.Enchanting.Minute.%{_uuid}%} to 1
				set {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} to true

			if {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} is not set:
				set {Strength.Power2.Enchanting.Second.%{_uuid}%} to 59
				set {Strength.Power2.Enchanting.Minute.%{_uuid}%} to 1
				set {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} to true

			if {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				set {Strength.Power2.Enchanting.Display.%{_uuid}%} to " &b%{Strength.Power2.Enchanting.Minute.%{_uuid}%}%m %{Strength.Power2.Enchanting.Second.%{_uuid}%}%s"
			
			if {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				remove 1 from {Strength.Power2.Enchanting.Second.%{_uuid}%}


			
			if {Strength.Power2.Enchanting.Second.%{_uuid}%} is -1:
				remove 1 from {Strength.Power2.Enchanting.Minute.%{_uuid}%}
				set {Strength.Power2.Enchanting.Second.%{_uuid}%} to 59
                
			if {Strength.Power2.Enchanting.Minute.%{_uuid}%} is -1:
				set {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} to false

				set {Strength.Power2.Enchanting.Display.%{_uuid}%} to " &aReady!"

			if {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} is false:
				set {Strength.Power2.Enchanting.Display.%{_uuid}%} to " &aReady!"

			#Frailer





			if {Strength.Power1.Frailer.Cooldown.%{_uuid}%} is true:
				remove 1 from {Strength.Power1.Frailer.Second.%{_uuid}%}


			
			if {Strength.Power1.Frailer.Second.%{_uuid}%} is -1:
				remove 1 from {Strength.Power1.Frailer.Minute.%{_uuid}%}
				set {Strength.Power1.Frailer.Second.%{_uuid}%} to 59


			if {Strength.Power1.Frailer.Second.%{_uuid}%} is not set:
				set {Strength.Power1.Frailer.Second.%{_uuid}%} to 59
				set {Strength.Power1.Frailer.Minute.%{_uuid}%} to 1
				set {Strength.Power1.Frailer.Cooldown.%{_uuid}%} to true

			if {Strength.Power1.Frailer.Display.%{_uuid}%} is not set:
				set {Strength.Power1.Frailer.Second.%{_uuid}%} to 59
				set {Strength.Power1.Frailer.Minute.%{_uuid}%} to 1
				set {Strength.Power1.Frailer.Cooldown.%{_uuid}%} to true

                
			if {Strength.Power1.Frailer.Cooldown.%{_uuid}%} is true:
				set {Strength.Power1.Frailer.Display.%{_uuid}%} to "🤺 &b%{Strength.Power1.Frailer.Minute.%{_uuid}%}%m %{Strength.Power1.Frailer.Second.%{_uuid}%}%s"



			if {Strength.Power1.Frailer.Minute.%{_uuid}%} is -1:
				set {Strength.Power1.Frailer.Cooldown.%{_uuid}%} to false
				set {Strength.Power1.Frailer.Second.%{_uuid}%} to 59
				set {Strength.Power1.Frailer.Minute.%{_uuid}%} to 1
				set {Strength.Power1.Frailer.Display.%{_uuid}%} to "🤺 &aReady!"




			if {Tag..%loop-player%} is not set:
				set {Tag..%loop-player%} to 0

			if loop-player's off hand item or loop-player's held item is a amethyst shard named "&4&lStrength &e&lgem":

				send action bar "&c🔺 %{Strength.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player
			


			if loop-player's off hand item is prismarine shard named "&4&lStrength &e&lgem":

				send action bar "%{Strength.Power1.Frailer.Display.%{_uuid}%}% &4🔮%{Strength.Power2.Enchanting.Display.%{_uuid}%}% %{Strength.Power3.Chad.Display.%{_uuid}%}%" to loop-player
		
			if loop-player's held item or loop-player's held item is a amethyst shard named "&4&lStrength &e&lgem":

				send action bar "&c🔺 %{Strength.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player



			if loop-player's held item is prismarine shard named "&4&lStrength &e&lgem":

				send action bar "%{Strength.Power1.Frailer.Display.%{_uuid}%}% &4🔮%{Strength.Power2.Enchanting.Display.%{_uuid}%}% %{Strength.Power3.Chad.Display.%{_uuid}%}%" to loop-player





on sneak toggle:
	if {Tag..%player%} is 0:
		set {_uuid} to uuid of player
		if player's off hand item is a amethyst shard named "&4&lStrength &e&lgem":

			if {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} is false:
				execute console command "enchant %player% sharpness 2"
				send "&aEnchanting Tool with &csharpness &42"
				set {Strength.Power2.Enchanting.Minute.%{_uuid}%} to 1
				set {Strength.Power2.Enchanting.Second.%{_uuid}%} to 59
				set {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} to true
		if player's off hand item is a prismarine shard named "&4&lStrength &e&lgem":

			if {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} is false:
				if player's held item is any sword:
					enchant the player's tool with sharpness 5
					send "&c🔮&bEnchanting Tool"
					set {Strength.Power2.Enchanting.Minute.%{_uuid}%} to 1
					set {Strength.Power2.Enchanting.Second.%{_uuid}%} to 59
					set {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} to true
				if player's held item is any axe:
					enchant the player's tool with sharpness 5
					send "&c🔮&bEnchanting Tool"
					set {Strength.Power2.Enchanting.Minute.%{_uuid}%} to 1
					set {Strength.Power2.Enchanting.Second.%{_uuid}%} to 59
					set {Strength.Power2.Enchanting.Cooldown.%{_uuid}%} to true




on damage:	
	if {Tag..%attacker%} is 0:
		if {Bliss.Strength.%attacker%} > 0:
			if attacker's off hand item is a prismarine shard named "&4&lStrength &e&lgem":
				if attacker's health < 3:
					add 8 to damage
				if attacker's health is 3:
					add 4.5 to damage
				if attacker's health is 3.5:
					add 4 to damage
				if attacker's health is 4:
					add 3.5 to damage
				if attacker's health is 4.5:
					add 2.5 to damage
				if attacker's health is 5:
					add 2 to damage
				if attacker's health is 5.5:
					add 1.5 to damage
				if attacker's health is 6:
					add 1 to damage
				if attacker's health is 6.5:
					add 0.5 to damage
			if attacker's off hand item is a amethyst shard named "&4&lStrength &e&lgem":
				if attacker's health < 2:
					add 6 to damage
				if attacker's health is 2.5:
					add 5.5 to damage
				if attacker's health is 3:
					add 4.5 to damage
				if attacker's health is 3.5:
					add 4 to damage
				if attacker's health is 4:
					add 3.5 to damage
				if attacker's health is 4.5:
					add 2.5 to damage
				if attacker's health is 5:
					add 2 to damage
				if attacker's health is 5.5:
					add 1.5 to damage
				if attacker's health is 6:
					add 1 to damage
				if attacker's health is 6.5:
					add 0.5 to damage



on right click on entity:
	if {Tag..%player%} is 0:
		if player's held item is a prismarine shard named "&4&lStrength &e&lgem":
			set {_uuid} to uuid of player
			if event-entity is a player:
				if {Strength.Power1.Frailer.Cooldown.%{_uuid}%} is false:
					send "&byou used &4Frailer &fon &4%event-entity%" to player
					send "&byou have been affected by &4Frailer &bfrom %player%" to event-entity
					execute console command "effect clear %event-entity%"
					apply weakness to event-entity for 20 seconds
					execute player command "/strengthcircle 0.5"
					execute player command "/strengthcircle 1"
					execute player command "/strengthcircle 1.5"
					execute player command "/strengthcircle 2"
					execute player command "/strengthcircle 2.5"
					execute player command "/strengthcircle 3"
					execute player command "/strengthcircle 3.5"
					if {Bliss.Strength.%player%} > 4:
						set {Strength.Power1.Frailer.Minute.%{_uuid}%} to 1
						set {Strength.Power1.Frailer.Second.%{_uuid}%} to 15
						set {Strength.Power1.Frailer.Cooldown.%{_uuid}%} to true
					if {Bliss.Strength.%player%} is 3:
						set {Strength.Power1.Frailer.Minute.%{_uuid}%} to 1
						set {Strength.Power1.Frailer.Second.%{_uuid}%} to 45
						set {Strength.Power1.Frailer.Cooldown.%{_uuid}%} to true
					if {Bliss.Strength.%player%} < 3:
						set {Strength.Power1.Frailer.Minute.%{_uuid}%} to 2
						set {Strength.Power1.Frailer.Second.%{_uuid}%} to 25
						set {Strength.Power1.Frailer.Cooldown.%{_uuid}%} to true

                            

on drop prismarine shard:
	if event-item is prismarine shard named "&4&lStrength &e&lgem":
		cancel event
on drop amethyst shard:
	if event-item is amethyst shard named "&4&lStrength &e&lgem":
		cancel event

every 4 ticks:
	loop all players:
		if {ChadStrength..%loop-player%} is true:
			draw 5 of dust using dustOption(dark red, 1) at loop-player
			execute console command "execute as %loop-player% at @s run particle dust 0.33 0.33 0.33 1 ^ ^.7 ^1 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0.33 0.33 0.33 1 ^ ^.7 ^-1 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0.33 0.33 0.33 1 ^1 ^.7 ^ 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0.33 0.33 0.33 1 ^-1 ^.7 ^ 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0 0 0 1 ^ ^.7 ^1 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0 0 0 1 ^ ^.7 ^-1 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0 0 0 1 ^1 ^.7 ^ 0 0 0 0 10 force @a"
			execute console command "execute as %loop-player% at @s run particle dust 0 0 0 1 ^-1 ^.7 ^ 0 0 0 0 10 force @a"


on damage:
	if {dmg..%attacker%} > 11:
		set {dmg..%attacker%} to 12
	if {ChadStrength..%attacker%} is true:
		fall distance of attacker is less than 0.7:
			if {dmg..%attacker%} > 14:
				set {dmg..%attacker%} to 14
			if {Test.Double.%attacker%} is 3:
				add {dmg..%attacker%} to damage
				set {dmg..%attacker%} to damage
				set {Test.Double.%attacker%} to 0
				set {ChadSkill...%attacker%} to false
				set {ChadSkill...%attacker%} to false
				set {ChadStrength..%attacker%} to false
			if {Test.Double.%attacker%} is 2:
				set {dmg..%attacker%} to damage
				add 1 to {Test.Double.%attacker%}
			if {Test.Double.%attacker%} is 1:
				set {dmg..%attacker%} to damage
				add 1 to {Test.Double.%attacker%}
			if {Test.Double.%attacker%} < 1:
				set {dmg..%attacker%} to damage
				add 1 to {Test.Double.%attacker%}




on left click:
	if {Tag..%player%} is 0:
		if player's held item is a prismarine shard named "&4&lStrength &e&lgem":
			set {_uuid} to uuid of player
			if {Strength.Power3.Chad.Cooldown.%{_uuid}%} is false:
				set {Test.Double.%player%} to 0
				send "&4⚔&cYou activated &4Chad Strength &bGroup"
				set {Doubledamage.%player%} to -5
				set {ChadStrength..%player%} to true
				if {Bliss.Strength.%player%} > 4:
					set {Strength.Power3.Chad.Minute.%{_uuid}%} to 2
					set {Strength.Power3.Chad.Second.%{_uuid}%} to 30
					set {Strength.Power3.Chad.Cooldown.%{_uuid}%} to true
				if {Bliss.Strength.%player%} is 3:
					set {Strength.Power3.Chad.Minute.%{_uuid}%} to 3
					set {Strength.Power3.Chad.Second.%{_uuid}%} to 1
					set {Strength.Power3.Chad.Cooldown.%{_uuid}%} to true
				if {Bliss.Strength.%player%} < 3:
					set {Strength.Power3.Chad.Minute.%{_uuid}%} to 3
					set {Strength.Power3.Chad.Second.%{_uuid}%} to 35
					set {Strength.Power3.Chad.Cooldown.%{_uuid}%} to true

			if {ChadStrength..%player%} is true:
				set {ChadStrength...%player%} to true


on left click:
	if {Tag..%player%} is 0:
		if player's held item is a prismarine shard named "&4&lStrength &e&lgem":
			if {Strength.Power3.Chad.Cooldown.%{_uuid}%} is false:
				wait 10 seconds
				set {ChadStrength...%player%} to false
				set {ChadStrength..%player%} to false


every 1 second:
	loop all players:
		if loop-player's off hand item is a amethyst shard named "&4&lStrength &e&lgem":
			apply potion of strength of tier 1 to loop-player for 1.03 second

		if loop-player's held item is a amethyst shard named "&4&lStrength &e&lgem":
			apply potion of strength of tier 1 to loop-player for 1.03 seconds

		if loop-player's off hand item is a prismarine shard named "&4&lStrength &e&lgem":
			apply potion of strength of tier 2 to loop-player for 1.03 seconds

		if loop-player's held item is a prismarine shard named "&4&lStrength &e&lgem":
			apply potion of strength of tier 2 to loop-player for 1.03 seconds