on respawn:
	if {Bliss.Strength.%player%} is 1:
		give player amethyst shard with custom model data 95 named "&4&lStrength &e&lgem" with lore "&4Broken Gem", "&aAuto enchant's swords with sharpness 2/4", "." and "&dPasive Strength" 
	if {Bliss.Strength.%player%} is 2:
		give player amethyst shard with custom model data 89 named "&4&lStrength &e&lgem" with lore "&cRuined Gem", "&aAuto enchant's swords with sharpness 2/4", "." and "&dPasive Strength"
	if {Bliss.Strength.%player%} is 3:
		give player amethyst shard with custom model data 69 named "&4&lStrength &e&lgem" with lore "&eDamaged Gem", "&aAuto enchant's swords with sharpness 2/4", "." and "&dPasive Strength" 
	if {Bliss.Strength.%player%} is 4:
		give player amethyst shard with custom model data 49 named "&4&lStrength &e&lgem" with lore "&aCracked Gem", "&aAuto enchant's swords with sharpness 2/4", "." and "&dPasive Strength" 
	if {Bliss.Strength.%player%} is 5:
		give player amethyst shard with custom model data 29 named "&4&lStrength &e&lgem" with lore "&aScratched Gem", "&aAuto enchant's swords with sharpness 2/4", "." and "&dPasive Strength" 
	if {Bliss.Strength.%player%} is 6:
		give player amethyst shard with custom model data 9 named "&4&lStrength &e&lgem" with lore "&bPristine Gem", "&aAuto enchant's swords with sharpness 2/4", "." and "&dPasive Strength" 
	if {Bliss.Strength.%player%} is 7:
		give player amethyst shard with custom model data 9 named "&4&lStrength &e&lgem" with lore "&bPristine + Gem", "&aAuto enchant's swords with sharpness 2/4", "." and "&dPasive Strength"
	if {Bliss.Strength.%player%} is 8:
		give player amethyst shard with custom model data 9 named "&4&lStrength &e&lgem" with lore "&bPristine + 2 Gem", "&aAuto enchant's swords with sharpness 2/4", "." and "&dPasive Strength" 
	if {Bliss.Strength.%player%} is 9:
		give player amethyst shard with custom model data 9 named "&4&lStrength &e&lgem" with lore "&bPristine + 3 Gem", "&aAuto enchant's swords with sharpness 2/4", "." and "&dPasive Strength" 
	if {Bliss.Strength.%player%} is 10:
		give player amethyst shard with custom model data 9 named "&4&lStrength &e&lgem" with lore "&bPristine + 4 Gem", "&aAuto enchant's swords with sharpness 2/4", "." and "&dPasive Strength"
	if {Bliss.Strength.%player%} > 10:
		set {item} to amethyst shard with custom model data 9 named "&4&lStrength &e&lgem" with lore "&bPristine + 5 Gem", "&aAuto enchant's swords with sharpness 2/4", "." and "&dPasive Strength" 
		give player {item}
		enchant {item} with mending 1
