#ᴀsᴛʀᴀ ɢᴇᴍ




every 1 tick:
	loop all players:
		set {_uuid} to uuid of loop-player
		
		if loop-player's off hand item is a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
			send action bar "<##A01FFF>🔺%{Astra.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player

		if loop-player's held item is a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":  
			send action bar "<##A01FFF>🔺%{Astra.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player
		



		if loop-player's off hand item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":

			send action bar "%{Astra.Power1.Daggers.Display.%{_uuid}%}% <##A01FFF>🔮 %{entity3.%loop-player%}%  &f%{Astra.Power3.Projection.Display.%{_uuid}%}%" to loop-player
		
		if loop-player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
			send action bar "%{Astra.Power1.Daggers.Display.%{_uuid}%}% <##A01FFF>🔮 %{entity3.%loop-player%}%  &f%{Astra.Power3.Projection.Display.%{_uuid}%}%" to loop-player



every 1 second:
	loop all players:
		if loop-player has a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
			set {_uuid} to uuid of loop-player

			#Daggers
			
			if {Astra.Power1.Daggers.Second.%{_uuid}%} is not set:
				set {Astra.Power1.Daggers.Second.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true

			if {Astra.Power1.Daggers.Minute.%{_uuid}%} is not set:
				set {Astra.Power1.Daggers.Second.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true

			if {Astra.Power1.Daggers.Cooldown.%{_uuid}%} is not set:
				set {Astra.Power1.Daggers.Second.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true

			if {Astra.Power1.Daggers.Display.%{_uuid}%} is not set:
				set {Astra.Power1.Daggers.Display.%{_uuid}%} to "🔪 &b%{Astra.Power1.Daggers.Minute.%{_uuid}%}%m %{Astra.Power1.Daggers.Second.%{_uuid}%}%s"
				
		
			if {Astra.Power1.Daggers.Cooldown.%{_uuid}%} is true:
				if {Astra.Power1.Daggers.Minute.%{_uuid}%} is 0:
					set {Astra.Power1.Daggers.Display.%{_uuid}%} to "🔪 &b%{Astra.Power1.Daggers.Second.%{_uuid}%}%s"

				else:
					set {Astra.Power1.Daggers.Display.%{_uuid}%} to "🔪 &b%{Astra.Power1.Daggers.Minute.%{_uuid}%}%m %{Astra.Power1.Daggers.Second.%{_uuid}%}%s"


			if {Astra.Power1.Daggers.Cooldown.%{_uuid}%} is true:
				remove 1 from {Astra.Power1.Daggers.Second.%{_uuid}%}



			if {Astra.Power1.Daggers.Second.%{_uuid}%} < 0:
				remove 1 from {Astra.Power1.Daggers.Minute.%{_uuid}%}
				set {Astra.Power1.Daggers.Second.%{_uuid}%} to 59
                
			if {Astra.Power1.Daggers.Minute.%{_uuid}%} < 0: 
				set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to false
				set {Astra.Power1.Daggers.Display.%{_uuid}%} to "🔪 &aReady!"


			#Enchanting

			if {Astra.Power2.Enchanting.Second.%{_uuid}%} is not set:
				set {Astra.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} to true

			if {Astra.Power2.Enchanting.Minute.%{_uuid}%} is not set:
				set {Astra.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} to true



			if {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} is not set:
				set {Astra.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} to true	
				set {Astra.Power2.Enchanting.Display.%{_uuid}%} to " &b%{Astra.Power2.Enchanting.Minute.%{_uuid}%}%m %{Astra.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Astra.Power2.Enchanting.Display.%{_uuid}%} is not set:
				set {Astra.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} to true	

			if {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				set {Astra.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Astra.Power2.Enchanting.Minute.%{_uuid}%}%m %{Astra.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Astra.Power2.Enchanting.Display.%{_uuid}%} is not set:
				set {Astra.Power2.Enchanting.Display.%{_uuid}%} to " &b %{Astra.Power2.Enchanting.Minute.%{_uuid}%}%m %{Astra.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				if {Astra.Power2.Enchanting.Minute.%{_uuid}%} is 0:
					set {Astra.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Astra.Power2.Enchanting.Second.%{_uuid}%}%s"

				else:
					set {Astra.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Astra.Power2.Enchanting.Minute.%{_uuid}%}%m %{Astra.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				remove 1 from {Astra.Power2.Enchanting.Second.%{_uuid}%}


			
			if {Astra.Power2.Enchanting.Second.%{_uuid}%} < 0:
				remove 1 from {Astra.Power2.Enchanting.Minute.%{_uuid}%}
				set {Astra.Power2.Enchanting.Second.%{_uuid}%} to 59
                
			if {Astra.Power2.Enchanting.Minute.%{_uuid}%} < 0:
				set {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} to false
				set {Astra.Power2.Enchanting.Display.%{_uuid}%} to " &aReady!"



			#Projection





			if {Astra.Power3.Projection.Cooldown.%{_uuid}%} is true:
				remove 1 from {Astra.Power3.Projection.Second.%{_uuid}%}


			
			if {Astra.Power3.Projection.Second.%{_uuid}%} < 0:
				remove 1 from {Astra.Power3.Projection.Minute.%{_uuid}%}
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 59


			if {Astra.Power3.Projection.Cooldown.%{_uuid}%} is true:
				if {Astra.Power3.Projection.Minute.%{_uuid}%} is 0:
					set {Astra.Power3.Projection.Display.%{_uuid}%} to "👻 &b%{Astra.Power3.Projection.Second.%{_uuid}%}%s"

				else:
					set {Astra.Power3.Projection.Display.%{_uuid}%} to "👻 &b%{Astra.Power3.Projection.Minute.%{_uuid}%}%m %{Astra.Power3.Projection.Second.%{_uuid}%}%s"


			if {Astra.Power3.Projection.Second.%{_uuid}%} is not set:
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0

			if {Astra.Power3.Projection.Cooldown.%{_uuid}%} is not set:
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true	
				set {Astra.Power3.Projection.Display.%{_uuid}%} to "👻 &b%{Astra.Power3.Projection.Minute.%{_uuid}%}%m %{Astra.Power3.Projection.Second.%{_uuid}%}%s"

			if {Astra.Power3.Projection.Display.%{_uuid}%} is not set:
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true	



			if {Astra.Power3.Projection.Display.%{_uuid}%} is not set:
				set {Astra.Power3.Projection.Display.%{_uuid}%} to "👻 &b%{Astra.Power3.Projection.Minute.%{_uuid}%}%m %{Astra.Power3.Projection.Second.%{_uuid}%}%s"

                




			if {Astra.Power3.Projection.Minute.%{_uuid}%} < 0:
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to false
				set {Astra.Power3.Projection.Display.%{_uuid}%} to "👻 &aReady!"



			# Set Stuff

			if {entity3.%loop-player%} is not set:
				set {entity3.%loop-player%} to ""


			if loop-player's off hand item is a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
				send action bar "<##A01FFF>🔺%{Astra.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player

			if loop-player's held item is a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":  
				send action bar "<##A01FFF>🔺%{Astra.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player
		



			if loop-player's off hand item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":

				send action bar "%{Astra.Power1.Daggers.Display.%{_uuid}%}% <##A01FFF>🔮 %{entity3.%loop-player%}%  &f%{Astra.Power3.Projection.Display.%{_uuid}%}%" to loop-player
		
			if loop-player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
				send action bar "%{Astra.Power1.Daggers.Display.%{_uuid}%}% <##A01FFF>🔮 %{entity3.%loop-player%}%  &f%{Astra.Power3.Projection.Display.%{_uuid}%}%" to loop-player








every 1 second:
	loop all players:
		if loop-player has a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
			set {_uuid} to uuid of loop-player

			#Daggers
			
			if {Astra.Power1.Daggers.Second.%{_uuid}%} is not set:
				set {Astra.Power1.Daggers.Second.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true

			if {Astra.Power1.Daggers.Minute.%{_uuid}%} is not set:
				set {Astra.Power1.Daggers.Second.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true

			if {Astra.Power1.Daggers.Cooldown.%{_uuid}%} is not set:
				set {Astra.Power1.Daggers.Second.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 0
				set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true

			if {Astra.Power1.Daggers.Display.%{_uuid}%} is not set:
				set {Astra.Power1.Daggers.Display.%{_uuid}%} to "🔪 &b%{Astra.Power1.Daggers.Minute.%{_uuid}%}%m %{Astra.Power1.Daggers.Second.%{_uuid}%}%s"
				
		
			if {Astra.Power1.Daggers.Cooldown.%{_uuid}%} is true:
				if {Astra.Power1.Daggers.Minute.%{_uuid}%} is 0:
					set {Astra.Power1.Daggers.Display.%{_uuid}%} to "🔪 &b%{Astra.Power1.Daggers.Second.%{_uuid}%}%s"

				else:
					set {Astra.Power1.Daggers.Display.%{_uuid}%} to "🔪 &b%{Astra.Power1.Daggers.Minute.%{_uuid}%}%m %{Astra.Power1.Daggers.Second.%{_uuid}%}%s"


			if {Astra.Power1.Daggers.Cooldown.%{_uuid}%} is true:
				remove 1 from {Astra.Power1.Daggers.Second.%{_uuid}%}



			if {Astra.Power1.Daggers.Second.%{_uuid}%} < 0:
				remove 1 from {Astra.Power1.Daggers.Minute.%{_uuid}%}
				set {Astra.Power1.Daggers.Second.%{_uuid}%} to 59
                
			if {Astra.Power1.Daggers.Minute.%{_uuid}%} < 0: 
				set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to false
				set {Astra.Power1.Daggers.Display.%{_uuid}%} to "🔪 &aReady!"


			#Enchanting

			if {Astra.Power2.Enchanting.Second.%{_uuid}%} is not set:
				set {Astra.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} to true

			if {Astra.Power2.Enchanting.Minute.%{_uuid}%} is not set:
				set {Astra.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} to true



			if {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} is not set:
				set {Astra.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} to true	
				set {Astra.Power2.Enchanting.Display.%{_uuid}%} to " &b%{Astra.Power2.Enchanting.Minute.%{_uuid}%}%m %{Astra.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Astra.Power2.Enchanting.Display.%{_uuid}%} is not set:
				set {Astra.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} to true	

			if {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				set {Astra.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Astra.Power2.Enchanting.Minute.%{_uuid}%}%m %{Astra.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Astra.Power2.Enchanting.Display.%{_uuid}%} is not set:
				set {Astra.Power2.Enchanting.Display.%{_uuid}%} to " &b %{Astra.Power2.Enchanting.Minute.%{_uuid}%}%m %{Astra.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				if {Astra.Power2.Enchanting.Minute.%{_uuid}%} is 0:
					set {Astra.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Astra.Power2.Enchanting.Second.%{_uuid}%}%s"

				else:
					set {Astra.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Astra.Power2.Enchanting.Minute.%{_uuid}%}%m %{Astra.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				remove 1 from {Astra.Power2.Enchanting.Second.%{_uuid}%}


			
			if {Astra.Power2.Enchanting.Second.%{_uuid}%} < 0:
				remove 1 from {Astra.Power2.Enchanting.Minute.%{_uuid}%}
				set {Astra.Power2.Enchanting.Second.%{_uuid}%} to 59
                
			if {Astra.Power2.Enchanting.Minute.%{_uuid}%} < 0:
				set {Astra.Power2.Enchanting.Cooldown.%{_uuid}%} to false
				set {Astra.Power2.Enchanting.Display.%{_uuid}%} to " &aReady!"



			#Projection





			if {Astra.Power3.Projection.Cooldown.%{_uuid}%} is true:
				remove 1 from {Astra.Power3.Projection.Second.%{_uuid}%}


			
			if {Astra.Power3.Projection.Second.%{_uuid}%} < 0:
				remove 1 from {Astra.Power3.Projection.Minute.%{_uuid}%}
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 59


			if {Astra.Power3.Projection.Cooldown.%{_uuid}%} is true:
				if {Astra.Power3.Projection.Minute.%{_uuid}%} is 0:
					set {Astra.Power3.Projection.Display.%{_uuid}%} to "👻 &b%{Astra.Power3.Projection.Second.%{_uuid}%}%s"

				else:
					set {Astra.Power3.Projection.Display.%{_uuid}%} to "👻 &b%{Astra.Power3.Projection.Minute.%{_uuid}%}%m %{Astra.Power3.Projection.Second.%{_uuid}%}%s"


			if {Astra.Power3.Projection.Second.%{_uuid}%} is not set:
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0

			if {Astra.Power3.Projection.Cooldown.%{_uuid}%} is not set:
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true	
				set {Astra.Power3.Projection.Display.%{_uuid}%} to "👻 &b%{Astra.Power3.Projection.Minute.%{_uuid}%}%m %{Astra.Power3.Projection.Second.%{_uuid}%}%s"

			if {Astra.Power3.Projection.Display.%{_uuid}%} is not set:
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true	



			if {Astra.Power3.Projection.Display.%{_uuid}%} is not set:
				set {Astra.Power3.Projection.Display.%{_uuid}%} to "👻 &b%{Astra.Power3.Projection.Minute.%{_uuid}%}%m %{Astra.Power3.Projection.Second.%{_uuid}%}%s"

                




			if {Astra.Power3.Projection.Minute.%{_uuid}%} < 0:
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to false
				set {Astra.Power3.Projection.Display.%{_uuid}%} to "👻 &aReady!"



			# Set Stuff

			if {entity3.%loop-player%} is not set:
				set {entity3.%loop-player%} to ""




			if loop-player's off hand item is a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
				send action bar "<##A01FFF>🔺%{Astra.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player

			if loop-player's held item is a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":  
				send action bar "<##A01FFF>🔺%{Astra.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player
		



			if loop-player's off hand item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":

				send action bar "%{Astra.Power1.Daggers.Display.%{_uuid}%}% <##A01FFF>🔮 %{entity3.%loop-player%}%  &f%{Astra.Power3.Projection.Display.%{_uuid}%}%" to loop-player
		
			if loop-player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
				send action bar "%{Astra.Power1.Daggers.Display.%{_uuid}%}% <##A01FFF>🔮 %{entity3.%loop-player%}%  &f%{Astra.Power3.Projection.Display.%{_uuid}%}%" to loop-player

on right click on player:
	if {ghoost...%player%} is true:
		if player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
			if {AstraProjection.%player%} is true:
				execute console command "tp @a[name=""%player%""] @e[tag=%player%Astra,limit=1]"
				execute console command "gamemode survival %player%"
				execute console command "execute as %player% at @s run item"
				execute console command "tag @a[tag=astrapart] remove astrapart"
				set {AstraProjection.%player%} to false
				set {Tag..%event-entity%} to 10
				wait 2 ticks
				execute console command "item replace entity @e[tag=%player%Astra] weapon.mainhand with air"
				execute console command "item replace entity @e[tag=%player%Astra] weapon.offhand with air"
				execute console command "kill @e[tag=%player%Astra]"

on join:
	set {Tag..%player%} to 0

on right click:
	set {_uuid} to uuid of player 
	if player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
		set {_uuid} to uuid of player
		if {Tag..%player%} is 0:
			set {_uuid} to uuid of player 
			if {Astra.Power3.Projection.Cooldown.%{_uuid}%} is true:
				execute console command "tp @a[name=""%player%""] @e[tag=%player%Astra,limit=1]"
				execute console command "gamemode survival %player%"
				execute console command "execute as %player% at @s run item"
				execute console command "tag @a[tag=astrapart] remove astrapart"
				wait 2 ticks
				execute console command "item replace entity @e[tag=%player%Astra] weapon.mainhand with air"
				execute console command "item replace entity @e[tag=%player%Astra] weapon.offhand with air"
				execute console command "kill @e[tag=%player%Astra]"
				send "👻 &5Astra Projection &fis on cooldown for &b%{Astra.Power3.Projection.Second.%{_uuid}%}%" to player
			if {Astra.Power3.Projection.Cooldown.%{_uuid}%} is false:
				spawn zombie at location of player
				set name of last spawned entity to "%player%"
				apply slowness 99 to last spawned entity for 2 minutes
				execute console command "item replace entity @e[name=""%player%""] armor.head from entity %player% armor.head"
				execute console command "item replace entity @e[name=""%player%""] armor.chest from entity %player% armor.chest"
				execute console command "item replace entity @e[name=""%player%""] armor.legs from entity %player% armor.legs"
				execute console command "item replace entity @e[name=""%player%""] armor.feet from entity %player% armor.feet"
				execute console command "item replace entity @e[name=""%player%""] weapon.mainhand from entity %player% weapon.mainhand"
				execute console command "item replace entity @e[name=""%player%""] weapon.offhand from entity %player% weapon.offhand"
				execute console command "tag @e[name=%player%] add %player%Astra"
				execute console command "tag %player% remove %player%Astra"
				execute console command "tag %player% add astrapart"
				set player's gamemode to spectator
				set {_uuid} to uuid of player
				set {Astra.Power3.Projection.Second.%{_uuid}%} to 30
				set {Astra.Power3.Projection.Minute.%{_uuid}%} to 0
				set {Astra.Power3.Projection.Cooldown.%{_uuid}%} to true

on teleport:
	if player's gamemode is spectator:
		cancel event
		
on damage:
	if victim is a zombie:
		execute console command "tp @a[name=""%victim%""] @e[tag=%victim%Astra,limit=1]"
		execute console command "gamemode survival %victim%"
		execute console command "execute as %victim% at @s run item"
		execute console command "tag @a[tag=astrapart] remove astrapart"
		wait 2 ticks
		execute console command "item replace entity @e[tag=%victim%Astra] weapon.mainhand with air"
		execute console command "item replace entity @e[tag=%victim%Astra] weapon.offhand with air"
		execute console command "kill @e[tag=%victim%Astra]"

every 1 tick:
	loop all players:
		if {AstraProjection.%loop-player%} is true:
			chance of 70%
			execute console command "execute as @e[tag=astrapart] at @s run particle dust 0.52 0.11 0.67 1 ~ ~1.2 ~ 0.1 0.1 0.1 1 1 normal"
		if {Shootdagger..%loop-player%} is 5:
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag] ^-1 ^-0.1 ^0.35 facing ^ ^ ^8"
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag2] ^1 ^-0.1 ^0.35 facing ^ ^ ^8"
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag3] ^-1.3 ^-0.1 ^1.5 facing ^ ^ ^8"
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag4] ^1.3 ^-0.1 ^1.5 facing ^ ^ ^8"
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag5] ^0.1 ^-0.1 ^2 facing ^ ^ ^8"
		if {Shootdagger..%loop-player%} is 4:
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag] ^-1 ^-0.1 ^0.35 facing ^ ^ ^8"
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag2] ^1 ^-0.1 ^0.35 facing ^ ^ ^8"
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag3] ^-1.3 ^-0.1 ^1.5 facing ^ ^ ^8"
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag4] ^1.3 ^-0.1 ^1.5 facing ^ ^ ^8"
		if {Shootdagger..%loop-player%} is 3:
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag] ^-1 ^-0.1 ^0.35 facing ^ ^ ^8"
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag2] ^1 ^-0.1 ^0.35 facing ^ ^ ^8"
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag3] ^-1.3 ^-0.1 ^1.5 facing ^ ^ ^8"
		if {Shootdagger..%loop-player%} is 2:
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag] ^-1 ^-0.1 ^0.35 facing ^ ^ ^8"
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag2] ^1 ^-0.1 ^0.35 facing ^ ^ ^8"
		if {Shootdagger..%loop-player%} is 1:
			execute console command "execute as %loop-player% at @s run tp @e[tag=%loop-player%dag] ^-1 ^-0.1 ^0.35 facing ^ ^ ^8"




function shootdagger5(p: player):
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^1 facing ^ ^ ^8"
	wait 0.2 seconds
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^1.1 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^1.2 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^1.3 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^1.4 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^1.5 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^1.6 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^1.7 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^1.8 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^1.9 facing ^ ^ ^10"






	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^2 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^2.1 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^2.2 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^2.3 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^2.4 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^2.5 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^2.6 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^2.7 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^2.8 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^2.9 facing ^ ^ ^11"




	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^3 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^3.1 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^3.2 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^3.3 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^3.4 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^3.5 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^3.6 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^3.7 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^3.8 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^3.9 facing ^ ^ ^12"






	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^4 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^4.1 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^4.2 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^4.3 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^4.4 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^4.5 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^4.6 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^4.7 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^4.8 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^4.9 facing ^ ^ ^13"





	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^5 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^5.1 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^5.2 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^5.3 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^5.4 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^5.5 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^5.6 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^5.7 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^5.8 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^5.9 facing ^ ^ ^14"




	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^6 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^6.1 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^6.2 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^6.3 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^6.4 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^6.5 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^6.6 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^6.7 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^6.8 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^6.9 facing ^ ^ ^15"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^7 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^7.1 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^7.2 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^7.3 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^7.4 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^7.5 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^7.6 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^7.7 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^7.8 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^7.9 facing ^ ^ ^16"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^8 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^8.1 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^8.2 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^8.3 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^8.4 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^8.5 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^8.6 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^8.7 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^8.8 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^8.9 facing ^ ^ ^17"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^9 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^9.1 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^9.2 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^9.3 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^9.4 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^9.5 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^9.6 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^9.7 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^9.8 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag5] ^0.07 ^-0.1 ^9.9 facing ^ ^ ^18"
	wait 0.27 second
	execute console command "kill @e[tag=%{_p}%dag5]"

function shootdagger4(p: player):
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^1 facing ^ ^ ^8"
	wait 0.2 seconds
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^1.1 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^1.2 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^1.3 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^1.4 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^1.5 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^1.6 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^1.7 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^1.8 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^1.9 facing ^ ^ ^10"






	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^2 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^2.1 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^2.2 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^2.3 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^2.4 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^2.5 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^2.6 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^2.7 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^2.8 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^2.9 facing ^ ^ ^11"




	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^3 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^3.1 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^3.2 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^3.3 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^3.4 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^3.5 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^3.6 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^3.7 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^3.8 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^3.9 facing ^ ^ ^12"






	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^4 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^4.1 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^4.2 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^4.3 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^4.4 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^4.5 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^4.6 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^4.7 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^4.8 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^4.9 facing ^ ^ ^13"





	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^5 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^5.1 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^5.2 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^5.3 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^5.4 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^5.5 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^5.6 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^5.7 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^5.8 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^5.9 facing ^ ^ ^14"




	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^6 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^6.1 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^6.2 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^6.3 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^6.4 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^6.5 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^6.6 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^6.7 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^6.8 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^6.9 facing ^ ^ ^15"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^7 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^7.1 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^7.2 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^7.3 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^7.4 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^7.5 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^7.6 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^7.7 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^7.8 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^7.9 facing ^ ^ ^16"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^8 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^8.1 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^8.2 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^8.3 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^8.4 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^8.5 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^8.6 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^8.7 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^8.8 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^8.9 facing ^ ^ ^17"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^9 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^9.1 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^9.2 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^9.3 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^9.4 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^9.5 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^9.6 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^9.7 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^9.8 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag4] ^0.07 ^-0.1 ^9.9 facing ^ ^ ^18"
	wait 0.27 second
	execute console command "kill @e[tag=%{_p}%dag4]"


function shootdagger3(p: player):
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^1 facing ^ ^ ^8"
	wait 0.2 seconds
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^1.1 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^1.2 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^1.3 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^1.4 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^1.5 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^1.6 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^1.7 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^1.8 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^1.9 facing ^ ^ ^10"






	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^2 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^2.1 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^2.2 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^2.3 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^2.4 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^2.5 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^2.6 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^2.7 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^2.8 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^2.9 facing ^ ^ ^11"




	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^3 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^3.1 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^3.2 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^3.3 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^3.4 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^3.5 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^3.6 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^3.7 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^3.8 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^3.9 facing ^ ^ ^12"






	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^4 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^4.1 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^4.2 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^4.3 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^4.4 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^4.5 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^4.6 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^4.7 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^4.8 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^4.9 facing ^ ^ ^13"





	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^5 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^5.1 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^5.2 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^5.3 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^5.4 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^5.5 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^5.6 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^5.7 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^5.8 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^5.9 facing ^ ^ ^14"




	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^6 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^6.1 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^6.2 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^6.3 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^6.4 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^6.5 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^6.6 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^6.7 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^6.8 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^6.9 facing ^ ^ ^15"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^7 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^7.1 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^7.2 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^7.3 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^7.4 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^7.5 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^7.6 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^7.7 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^7.8 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^7.9 facing ^ ^ ^16"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^8 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^8.1 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^8.2 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^8.3 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^8.4 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^8.5 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^8.6 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^8.7 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^8.8 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^8.9 facing ^ ^ ^17"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^9 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^9.1 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^9.2 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^9.3 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^9.4 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^9.5 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^9.6 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^9.7 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^9.8 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag3] ^0.07 ^-0.1 ^9.9 facing ^ ^ ^18"
	wait 0.27 second
	execute console command "kill @e[tag=%{_p}%dag3]"


function shootdagger2(p: player):
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^1 facing ^ ^ ^8"
	wait 0.2 seconds
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^1.1 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^1.2 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^1.3 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^1.4 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^1.5 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^1.6 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^1.7 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^1.8 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^1.9 facing ^ ^ ^10"






	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^2 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^2.1 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^2.2 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^2.3 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^2.4 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^2.5 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^2.6 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^2.7 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^2.8 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^2.9 facing ^ ^ ^11"




	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^3 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^3.1 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^3.2 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^3.3 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^3.4 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^3.5 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^3.6 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^3.7 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^3.8 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^3.9 facing ^ ^ ^12"






	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^4 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^4.1 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^4.2 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^4.3 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^4.4 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^4.5 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^4.6 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^4.7 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^4.8 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^4.9 facing ^ ^ ^13"





	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^5 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^5.1 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^5.2 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^5.3 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^5.4 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^5.5 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^5.6 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^5.7 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^5.8 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^5.9 facing ^ ^ ^14"




	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^6 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^6.1 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^6.2 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^6.3 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^6.4 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^6.5 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^6.6 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^6.7 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^6.8 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^6.9 facing ^ ^ ^15"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^7 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^7.1 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^7.2 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^7.3 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^7.4 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^7.5 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^7.6 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^7.7 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^7.8 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^7.9 facing ^ ^ ^16"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^8 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^8.1 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^8.2 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^8.3 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^8.4 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^8.5 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^8.6 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^8.7 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^8.8 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^8.9 facing ^ ^ ^17"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^9 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^9.1 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^9.2 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^9.3 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^9.4 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^9.5 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^9.6 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^9.7 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^9.8 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag2] ^0.07 ^-0.1 ^9.9 facing ^ ^ ^18"
	wait 0.27 second
	execute console command "kill @e[tag=%{_p}%dag2]"

function shootdagger1(p: player):
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^1 facing ^ ^ ^8"
	wait 0.2 seconds

	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^1.1 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^1.2 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^1.3 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^1.4 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^1.5 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^1.6 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^1.7 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^1.8 facing ^ ^ ^10"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^1.9 facing ^ ^ ^10"






	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^2 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^2.1 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^2.2 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^2.3 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^2.4 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^2.5 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^2.6 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^2.7 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^2.8 facing ^ ^ ^11"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^2.9 facing ^ ^ ^11"




	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^3 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^3.1 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^3.2 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^3.3 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^3.4 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^3.5 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^3.6 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^3.7 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^3.8 facing ^ ^ ^12"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^3.9 facing ^ ^ ^12"






	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^4 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^4.1 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^4.2 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^4.3 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^4.4 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^4.5 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^4.6 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^4.7 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^4.8 facing ^ ^ ^13"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^4.9 facing ^ ^ ^13"





	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^5 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^5.1 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^5.2 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^5.3 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^5.4 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^5.5 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^5.6 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^5.7 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^5.8 facing ^ ^ ^14"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^5.9 facing ^ ^ ^14"




	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^6 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^6.1 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^6.2 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^6.3 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^6.4 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^6.5 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^6.6 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^6.7 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^6.8 facing ^ ^ ^15"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^6.9 facing ^ ^ ^15"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^7 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^7.1 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^7.2 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^7.3 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^7.4 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^7.5 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^7.6 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^7.7 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^7.8 facing ^ ^ ^16"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^7.9 facing ^ ^ ^16"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^8 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^8.1 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^8.2 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^8.3 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^8.4 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^8.5 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^8.6 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^8.7 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^8.8 facing ^ ^ ^17"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^8.9 facing ^ ^ ^17"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^9 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^9.1 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^9.2 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^9.3 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^9.4 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^9.5 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^9.6 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^9.7 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^9.8 facing ^ ^ ^18"
	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^9.9 facing ^ ^ ^18"


	execute console command "execute as %{_p}% at @s run tp @e[tag=%{_p}%dag] ^0.07 ^-0.1 ^10 facing ^ ^ ^18"
	wait 0.27 second
	execute console command "kill @e[tag=%{_p}%dag]"


command /fix232:
	trigger:
		set {Shootdagger..%player%} to 0

on left click:
	if player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
		set {_uuid} to uuid of player
		if {Shootdagger..%player%} > 0:
			if {Shootdagger..%player%} is 5:
				shootdagger5(player)
				remove 1 from {Shootdagger..%player%}
			else if {Shootdagger..%player%} is 4:
				shootdagger4(player)
				remove 1 from {Shootdagger..%player%}
			else if {Shootdagger..%player%} is 3:
				shootdagger3(player)
				remove 1 from {Shootdagger..%player%}
			else if {Shootdagger..%player%} is 2:
				shootdagger2(player)
				remove 1 from {Shootdagger..%player%}
			else if {Shootdagger..%player%} is 1:
				shootdagger1(player)
				remove 1 from {Shootdagger..%player%}
			#shoot arrow at speed 2.5
			#if {Shootdagger..%player%} is 4:
				#execute console command "kill @e[tag=%player%dag5]"
			#if {Shootdagger..%player%} is 3:
				#execute console command "kill @e[tag=%player%dag4]"
			#if {Shootdagger..%player%} is 2:
				#execute console command "kill @e[tag=%player%dag3]"
			#if {Shootdagger..%player%} is 1:
				#execute console command "kill @e[tag=%player%dag2]"
			#if {Shootdagger..%player%} is 0:
				#execute console command "kill @e[tag=%player%dag]"
			wait 1 seconds
			set {Daggers.on.%{_uuid}%} to false
	if player's off hand item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
		set {_uuid} to uuid of player
		if {Tag..%player%} is 0:
			if {ghoost...%player%} is true:
				remove 0.1 from player's health
				set {ghoost...%player%} to false
	if player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
		set {_uuid} to uuid of player
		if {Tag..%player%} is 0:
			set {_uuid} to uuid of player
			if {Astra.Power1.Daggers.Cooldown.%{_uuid}%} is true:
				if {Astra.Power1.Daggers.Minute.%{_uuid}%} > 1 :
					if {Daggers.on.%{_uuid}%} is true:
						send "<##A01FFF>🔮 &cYour &rUnbounded &cskill is on cooldown for &5%{Astra.Power1.Daggers.Minute.%{_uuid}%}%m %{Astra.Power1.Daggers.Second.%{_uuid}%}%s"
				else:
					if {Daggers.on.%{_uuid}%} is true:
						send "<##A01FFF>🔮 &cYour &rUnbounded &cskill is on cooldown for &5%{Astra.Power1.Daggers.Second.%{_uuid}%}%s"
			if {Astra.Power1.Daggers.Cooldown.%{_uuid}%} is false:
				if {Shootdagger..%player%} is not set:
					set {Shootdagger..%player%} to 0
				if {Daggers.on.%{_uuid}%} is false:
					set {Daggers.on.%{_uuid}%} to true
					set {Shootdagger..%player%} to 5
					set {_uuid} to uuid of player
					if {Bliss.GemHealth.%{_uuid}%} > 3:
						set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 2
						set {Astra.Power1.Daggers.Second.%{_uuid}%} to 30
						set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true
					if {Bliss.GemHealth.%{_uuid}%} is 3:
						set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 2
						set {Astra.Power1.Daggers.Second.%{_uuid}%} to 30
						set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true
					if {Bliss.GemHealth.%{_uuid}%} < 3:
						set {Astra.Power1.Daggers.Minute.%{_uuid}%} to 2
						set {Astra.Power1.Daggers.Second.%{_uuid}%} to 30
						set {Astra.Power1.Daggers.Cooldown.%{_uuid}%} to true

					set {Daggers.1.%{_uuid}%} to an armor stand with nbt compound from "{Marker:1b,Invisible:1b,Tags:[""%player%dag"",""dag""],ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f]}"
					set {Daggers.2.%{_uuid}%} to an armor stand with nbt compound from "{Marker:1b,Invisible:1b,Tags:[""%player%dag2"",""dag2""],ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f]}"
					set {Daggers.3.%{_uuid}%} to an armor stand with nbt compound from "{Marker:1b,Invisible:1b,Tags:[""%player%dag3"",""dag3""],ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f]}"
					set {Daggers.4.%{_uuid}%} to an armor stand with nbt compound from "{Marker:1b,Invisible:1b,Tags:[""%player%dag4"",""dag4""],ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f]}"
					set {Daggers.5.%{_uuid}%} to an armor stand with nbt compound from "{Marker:1b,Invisible:1b,Tags:[""%player%dag5"",""dag5""],ArmorItems:[{},{},{},{id:nautilus_shell,tag:{CustomModelData:230},Count:1}],ArmorDropChances:[0f,0f,0f,0f]}"

					spawn {Daggers.1.%{_uuid}%} at location of player
					spawn {Daggers.2.%{_uuid}%} at location of player
					spawn {Daggers.3.%{_uuid}%} at location of player
					spawn {Daggers.4.%{_uuid}%} at location of player
					spawn {Daggers.5.%{_uuid}%} at location of player




					wait 1 second
					execute console command "item replace entity @e[tag=%player%dag5] armor.head with minecraft:nautilus_shell{Enchantments:[{id:""minecraft:sharpness"", lvl:0}],CustomModelData:230,display:{Name:'{\""text\"":\""AstraDagger5\"",\""italic\"":false}'}}"
					execute console command "item replace entity @e[tag=%player%dag4] armor.head with minecraft:nautilus_shell{Enchantments:[{id:""minecraft:sharpness"", lvl:0}],CustomModelData:230,display:{Name:'{\""text\"":\""AstraDagger4\"",\""italic\"":false}'}}"
					execute console command "item replace entity @e[tag=%player%dag3] armor.head with minecraft:nautilus_shell{Enchantments:[{id:""minecraft:sharpness"", lvl:0}],CustomModelData:230,display:{Name:'{\""text\"":\""AstraDagger3\"",\""italic\"":false}'}}"
					execute console command "item replace entity @e[tag=%player%dag2] armor.head with minecraft:nautilus_shell{Enchantments:[{id:""minecraft:sharpness"", lvl:0}],CustomModelData:230,display:{Name:'{\""text\"":\""AstraDagger2\"",\""italic\"":false}'}}"
					execute console command "item replace entity @e[tag=%player%dag] armor.head with minecraft:nautilus_shell{Enchantments:[{id:""minecraft:sharpness"", lvl:0}],CustomModelData:230,display:{Name:'{\""text\"":\""AstraDagger1\"",\""italic\"":false}'}}"








every 1 tick:
	loop all players:
		set {_uuid} to uuid of loop-player
		loop all entities in radius 200 of loop-player:
			loop all entities in radius 1.5 of loop-entity-2:
				if loop-entity-3 is not loop-entity-2:
					if loop-entity-3 is a armor stand:
						if loop-entity-3's helmet is a nautilus shell:
							set {_uuid} to uuid of loop-entity-2
							if {Daggers.1.%{_uuid}%} is not loop-entity-3:
								if {Daggers.2.%{_uuid}%} is not loop-entity-3:
									if {Daggers.3.%{_uuid}%} is not loop-entity-3:
										if {Daggers.4.%{_uuid}%} is not loop-entity-3:
											if {Daggers.5.%{_uuid}%} is not loop-entity-3:
												if loop-entity-2's helmet is not a nautilus shell:
													broadcast "%loop-entity-2% hitted"
													broadcast "%loop-entity-3% armor"
													set {LastAttacker..%loop-entity-2%} to {DaggerShotBy.%loop-entity-3%}
													damage loop-entity-2 by 6
													push loop-entity-2 backwards at speed 0.4
													push loop-entity-2 up at speed 0.2
													add 10 to {DisabledGem::%loop-entity-2%}
													kill loop-entity-3
													wait 5 seconds
													set {LastAttacker..%loop-entity-2%} to false
					#else:
					#if loop-entity-2's name is not "%{DaggerShotBy.%loop-entity-3%}%":
						#if loop-entity-3 is not loop-player:
							#if loop-entity-3 is armor stand:
							#	set {_uuid} to uuid of loop-entity-2
							#	if {Daggers.1.%{_uuid}%} is not loop-entity-3:
							#		if {Daggers.2.%{_uuid}%} is not loop-entity-3:
							#			if {Daggers.3.%{_uuid}%} is not loop-entity-3:
							#				if {Daggers.4.%{_uuid}%} is not loop-entity-3:
							#					if {Daggers.5.%{_uuid}%} is not loop-entity-3:
							#						set {LastAttacker..%loop-entity-2%} to {DaggerShotBy.%loop-entity-3%}
							#						damage loop-entity-2 by 6
							#						push loop-entity-2 backwards at speed 0.4
							#						push loop-entity-2 up at speed 0.2
							#						add 10 to {DisabledGem::%loop-entity-2%}
							#						kill loop-entity-3
							#						wait 5 seconds
							#						set {LastAttacker..%loop-entity-2%} to false








command /fixdaggers <player>:
	permission: op
	trigger:
		set {_uuid} to uuid of arg-1
		set {Daggers.on.%{_uuid}%} to false

every 1 tick:
	loop all players:
		if {Tag..%loop-player%} > 0:
			send action bar "🔒 &8&lDISABLED: %{Tag..%loop-player%}%s" to loop-player

every 1 second:
	loop all players:
		if {Tag..%loop-player%} > 0:
			apply darkness to loop-player for 1 second
			remove 1 from {Tag..%loop-player%}

	loop all players:
		set {_uuid} to uuid of loop-player
		if {Daggers.on.%{_uuid}%} is not set:
			set {Daggers.on.%{_uuid}%} to false


on damage:
	if victim has a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
		chance of 10%
		cancel event
		apply invisibility to victim for 15 ticks
	if victim has a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
		chance of 15%
		cancel event
		apply invisibility to victim for 15 ticks
on drop amethyst shard:
	cancel event
on drop prismarine shard:
	cancel event

on damage:
	if {ghoost...%victim%} is true:
		set victim's fly mode to false
		set {ghoost...%victim%} to false

on left click:
	if clicked block is set:
		if player's held item is a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
			if {Sneaky...%player%} is true:
				if {Entity,%player%} is 1:
					spawn {entity.%player%} 1 block above event-block
					remove 1 from {Entity,%player%} 
				if {Entity,%player%} is 2:
					spawn {entity2.%player%} 1 block above event-block
					remove 1 from {Entity,%player%} 
				if {Entity,%player%} is 3:
					spawn {entity3.%player%} 1 block above event-block
					remove 1 from {Entity,%player%}
		if player's held item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
			if {Sneaky...%player%} is true:
				if {Entity,%player%} is 1:
					spawn {entity.%player%} 1 block above event-block
					remove 1 from {Entity,%player%} 
				if {Entity,%player%} is 2:
					spawn {entity2.%player%} 1 block above event-block
					remove 1 from {Entity,%player%} 
				if {Entity,%player%} is 3:
					spawn {entity3.%player%} 1 block above event-block
					remove 1 from {Entity,%player%} 
				if {Entity,%player%} is 4:
					spawn {entity4.%player%} 1 block above event-block
					remove 1 from {Entity,%player%} 
				if {Entity,%player%} is 5:
					spawn {entity5.%player%} 1 block above event-block
					remove 1 from {Entity,%player%} 
on sneak toggle:
	set {Sneaky...%player%} to true
	wait 10 seconds
	set {Sneaky...%player%} to false

on right click on entity:
	if player's held item is a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
		if {Sneaky...%player%} is true:
			if event-entity is a villager:
				if {Entity,%player%} is 1:
					set {entity.%player%} to event-entity's type
				if {Entity,%player%} is 2:
					set {entity2.%player%} to event-entity's type
				if {Entity,%player%} is 3:
					set {entity3.%player%} to event-entity's type



on death:
	if attacker's off hand item is a amethyst shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
		if {Entity,%attacker%} is not 3:
			add 1 to {Entity,%attacker%}
			send "&c%{Entity,%attacker%}%" to attacker
		if victim is a zombie:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to zombie
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to zombie
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to zombie
		if victim is a powered creeper:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to powered creeper
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to powered creeper
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to powered creeper
		if victim is a skeleton:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to skeleton
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to skeleton
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to skeleton
		if victim is a spider:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to spider
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to spider
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to spider
		if victim is a warden:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to warden
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to warden
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to warden
		if victim is a villager:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to villager
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to villager
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to villager
		if victim is a wither skeleton:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to wither skeleton
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to wither skeleton
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to wither skeleton
		if victim is a chicken:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to chicken
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to chicken
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to chicken
		if victim is a piglin:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to piglin
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to piglin
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to piglin
		if victim is a creeper:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to  creeper
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to creeper
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to powered creeper
		if victim is a cow:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to cow
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to cow
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to cow
		if victim is a pig:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to pig
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to pig
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to pig
		if victim is a iron golem:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to iron golem
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to iron golem
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to iron golem
	if attacker's off hand item is a prismarine shard named "<##A01FFF>&lᴀsᴛʀᴀ &r<##C7C7C7>ɢᴇᴍ":
		if {Entity,%attacker%} is not 3:
			add 1 to {Entity,%attacker%}
			send "&c%{Entity,%attacker%}%" to attacker
		if victim is a zombie:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to zombie
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to zombie
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to zombie
		if victim is a powered creeper:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to powered creeper
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to powered creeper
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to powered creeper
		if victim is a skeleton:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to skeleton
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to skeleton
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to skeleton
		if victim is a spider:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to spider
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to spider
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to spider
		if victim is a warden:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to warden
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to warden
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to warden
		if victim is a villager:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to villager
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to villager
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to villager
		if victim is a wither skeleton:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to wither skeleton
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to wither skeleton
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to wither skeleton
		if victim is a chicken:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to chicken
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to chicken
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to chicken
		if victim is a piglin:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to piglin
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to piglin
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to piglin
		if victim is a creeper:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to creeper
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to creeper
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to creeper
		if victim is a cow:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to cow
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to cow
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to cow
		if victim is a pig:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to pig
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to pig
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to pig
		if victim is a iron golem:
			if {Entity,%attacker%} is 1:
				set {entity.%attacker%} to iron golem
			if {Entity,%attacker%} is 2:
				set {entity2.%attacker%} to iron golem
			if {Entity,%attacker%} is 3:
				set {entity3.%attacker%} to iron golem



