on death of player:
	wait 10 tick

	if {Bliss.Speed.%victim%} is 0:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &fN/A" to victim
	if {Bliss.Speed.%victim%} is 1:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &7Broken" to victim
	if {Bliss.Speed.%victim%} is 2:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &4Ruined" to victim
	if {Bliss.Speed.%victim%} is 3:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &eDamaged" to victim
	if {Bliss.Speed.%attacker%} is 4:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &aCracked" to victim
	if {Bliss.Speed.%attacker%} is 5:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &aScratched" to victim
	if {Bliss.Speed.%attacker%} is 6:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &bPristine" to victim
	if {Bliss.Speed.%attacker%} is 7:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &bPristine + 1" to victim
	if {Bliss.Speed.%attacker%} is 8:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &bPristine + 2" to victim
	if {Bliss.Strength.%attacker%} is 9:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &bPristine + 3" to victim
	if {Bliss.Speed.%attacker%} is 10:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &bPristine + 4" to victim
	if {Bliss.Speed.%attacker%} > 10:
		send "&bYou lost &cenergy. &byour &e&lsᴘᴇᴇᴅ &bgem is now at &bPristine + 5" to victim