on death of player:
	wait 1 tick

	if {Bliss.Wealth.%attacker%} is 0:
		send "&bYou lost &cenergy. &byour &2&lᴡᴇᴀʟᴛʜ &bgem is now at &fN/A" to victim
	if {Bliss.Wealth.%victim%} is 1:
		send "&bYou lost &cenergy. &byour &2&lᴡᴇᴀʟᴛʜ &bgem is now at &7Broken" to victim
	if {Bliss.Wealth.%victim%} is 2:
		send "&bYou lost &cenergy. &byour &2&lᴡᴇᴀʟᴛʜ &bgem is now at &4Ruined" to victim
	if {Bliss.Wealth.%victim%} is 3:
		send "&bYou lost &cenergy. &byour &2&lᴡᴇᴀʟᴛʜ &bgem is now at &eDamaged" to victim
	if {Bliss.Wealth.%victim%} is 4:
		send "&bYou lost &cenergy. &byour &2&lᴡᴇᴀʟᴛʜ &bgem is now at &aCracked" to victim
	if {Bliss.Wealth.%victim%} is 5:
		send "&bYou lost &cenergy. &byour &2&lᴡᴇᴀʟᴛʜ &bgem is now at &aScratched" to victim
	if {Bliss.Wealth.%victim%} is 6:
		send "&bYou lost &cenergy. &byour &2&lᴡᴇᴀʟᴛʜ &bgem is now at &bPristine" to victim
	if {Bliss.Wealth.%victim%} is 7:
		send "&bYou lost &cenergy. &byour &2&lᴡᴇᴀʟᴛʜ &bgem is now at &bPristine + 1" to victim
	if {Bliss.Wealth.%victim%} is 8:
		send "&bYou lost &cenergy. &byour &2&lᴡᴇᴀʟᴛʜ &bgem is now at &bPristine + 2" to victim
	if {Bliss.Wealth.%victim%} is 9:
		send "&bYou lost &cenergy. &byour &2&lᴡᴇᴀʟᴛʜ &bgem is now at &bPristine + 3" to victim
	if {Bliss.Wealth.%victim%} is 10:
		send "&bYou lost &cenergy. &byour &2&lᴡᴇᴀʟᴛʜ &bgem is now at &bPristine + 4" to victim