command /puffcircle <number> <player>: # number = Size of circle
    permission: op
    trigger:
        set {_pl} to location of arg-2
        set {_step} to 1 # Set a larger step value here
        set {_iterations} to 360 * arg-1 / {_step}
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v} with extra 0.000000001
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force


command /puffcirclelast <number> <player>: # number = Size of circle
    permission: op
    trigger:
        set {_pl} to location of arg-2
        set {_step} to 1 # Set a larger step value here
        set {_iterations} to 360 * arg-1 / {_step}

        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force
          
        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force


        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force


        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force


        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(white, white, 1) at {_pl} ~ {_v}
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force


command /pufflinelast <player> <player>: # number = Size of circle
    permission: op
    trigger:
        if {Particle_puff_%uuid of arg-2%} is true:
            set {_v} to vector from arg-1's head to arg-2's head
            set vector length of {_v} to 0.1
            set {_loc} to the location 0.7 meters under arg-1's head
            loop (distance between {_loc} and arg-2) / 0.1 times:

                draw 1 dust_color_transition using dustTransition(white, white, 2) at {_loc} with force
                set {_loc} to {_loc} ~ {_v}


command /pufflinelastfix <player>:
    permission: op
    trigger:
        set {Particle_puff_%uuid of arg-1%} to true