on respawn:
	if {Bliss.Puff.%player%} is 1:
		give player amethyst shard with custom model data 95 named "&f&lPuff &lgem" with lore "&4Broken Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
	if {Bliss.Puff.%player%} is 2:
		give player amethyst shard with custom model data 85 named "&f&lPuff &lgem" with lore "&cRuined Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
	if {Bliss.Puff.%player%} is 3:
		give player amethyst shard with custom model data 65 named "&f&lPuff &lgem" with lore "&dDamaged Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
	if {Bliss.Puff.%player%} is 4:
		give player amethyst shard with custom model data 45 named "&f&lPuff &lgem" with lore "&aCracked Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
	if {Bliss.Puff.%player%} is 5:
		give player amethyst shard with custom model data 25 named "&f&lPuff &lgem" with lore "&aScrached Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
	if {Bliss.Puff.%player%} is 6:
		give player amethyst shard with custom model data 5 named "&f&lPuff &lgem" with lore "&bPristine Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
	if {Bliss.Puff.%player%} is 7:
		give player amethyst shard with custom model data 5 named "&f&lPuff &lgem" with lore "&bPristine + Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
	if {Bliss.Puff.%player%} is 8:
		give player amethyst shard with custom model data 5 named "&f&lPuff &lgem" with lore "&bPristine + 2 Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
	if {Bliss.Puff.%player%} is 9:
		give player amethyst shard with custom model data 5 named "&f&lPuff &lgem" with lore "&bPristine + 3 Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
	if {Bliss.Puff.%player%} is 10:
		give player amethyst shard with custom model data 5 named "&f&lPuff &lgem" with lore "&bPristine + 4 Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
	if {Bliss.Puff.%player%} > 10:
		set {item} to amethyst shard with custom model data 5 named "&f&lPuff &lgem" with lore "&bPristine + 5 Gem", "&aDouble Jump 10s cooldown", "<red>" and "&fBreezy Bash Push enemys 60 blocks in the air and drop them fast", "&cDash 30 blocks in the air 1m 15s cooldown" and "&fImmune to Fall dmg" 
		give player {item}
		enchant {item} with mending 1