on death of player:
	if attacker's off hand item is a prismarine shard named "&2&lWealth &lgem":
		add 1 to {Bliss.Wealth.%attacker%} 
		if {Bliss.Wealth.%attacker%} < 2:
			set attacker's off hand item to prismarine shard named "&2&lWealth &lgem" with lore "&8Broken Gem", "&aAuto enchant's pickaxe and axe with fortune 1/3", "." and "&dPasive &aHero of the village" with custom model data 89
		if {Bliss.Wealth.%attacker%} is 2:
			set attacker's off hand item to prismarine shard named "&2&lWealth &lgem" with lore "&cRuined Gem", "&aAuto enchant's pickaxe and axe with fortune 1/3", "." and "&dPasive &aHero of the village" with custom model data 1102
		if {Bliss.Wealth.%attacker%} is 3:
			set attacker's off hand item to prismarine shard named "&2&lWealth &lgem" with lore "&eDamaged Gem", "&aAuto enchant's pickaxe and axe with fortune 1/3", "." and "&dPasive &aHero of the village" with custom model data 1102
		if {Bliss.Wealth.%attacker%} is 4:
			set attacker's off hand item to prismarine shard named "&2&lWealth &lgem" with lore "&aCracked Gem", "&aAuto enchant's pickaxe and axe with fortune 1/3", "." and "&dPasive &aHero of the village" with custom model data 1102
		if {Bliss.Wealth.%attacker%} is 5:
			set attacker's off hand item to prismarine shard named "&2&lWealth &lgem" with lore "&aScratched Gem", "&aAuto enchant's pickaxe and axe with fortune 1/3", "." and "&dPasive &aHero of the village" with custom model data 1105
		if {Bliss.Wealth.%attacker%} is 6:
			set attacker's off hand item to prismarine shard named "&2&lWealth &lgem" with lore "&bPristine Gem", "&aAuto enchant's pickaxe and axe with fortune 1/3", "." and "&dPasive &aHero of the village" with custom model data 1106
		if {Bliss.Wealth.%attacker%} is 7:
			set attacker's off hand item to prismarine shard named "&2&lWealth &lgem" with lore "&bPristine + Gem", "&aAuto enchant's pickaxe and axe with fortune 1/3", "." and "&dPasive &aHero of the village" with custom model data 1106
		if {Bliss.Wealth.%attacker%} is 8:
			set attacker's off hand item to prismarine shard named "&2&lWealth &lgem" with lore "&bPristine + 2 Gem", "&aAuto enchant's pickaxe and axe with fortune 1/3", "." and "&dPasive &aHero of the village" with custom model data 1106
		if {Bliss.Wealth.%attacker%} is 9:
			set attacker's off hand item to prismarine shard named "&2&lWealth &lgem" with lore "&bPristine + 3 Gem", "&aAuto enchant's pickaxe and axe with fortune 1/3", "." and "&dPasive &aHero of the village" with custom model data 1106
		if {Bliss.Wealth.%attacker%} is 10:
			set attacker's off hand item to prismarine shard named "&2&lWealth &lgem" with lore "&bPristine + 4 Gem", "&aAuto enchant's pickaxe and axe with fortune 1/3", "." and "&dPasive &aHero of the village" with custom model data 1106
		if {Bliss.Wealth.%attacker%} > 11:
			set {item} to prismarine shard with custom model data 12 named "&2&lWealth &lgem" with lore "&bPristine + 5 Gem", "&aAuto enchant's pickaxe and axe with fortune 1/3", "." and "&dPasive &aHero of the village"
			set attacker's off hand item to {item}
			enchant {item} with mending 1
