on death of player:
	wait 1 tick

	if {Bliss.Astra.%victim%} is 0:
		send "&bYou lost &cenergy. &byour &5&lᴀsᴛʀᴀ &bgem is now at &fN/A" to victim
	if {Bliss.Astra.%victim%} is 1:
		send "&bYou lost &cenergy. &byour &5&lᴀsᴛʀᴀ &bgem is now at &7Broken" to victim
	if {Bliss.Astra.%victim%} is 2:
		send "&bYou lost &cenergy. &byour &5&lᴀsᴛʀᴀ &bgem is now at &4Ruined" to victim
	if {Bliss.Astra.%victim%} is 3:
		send "&bYou lost &cenergy. &byour &5&lᴀsᴛʀᴀ &bgem is now at &eDamaged" to victim
	if {Bliss.Astra.%victim%} is 4:
		send "&byou lost &cenergy. &byour &5&lᴀsᴛʀᴀ &bgem is now at &aCracked" to victim
	if {Bliss.Astra.%victim%} is 5:
		send "&bYou lost &cenergy. &byour &5&lᴀsᴛʀᴀ &bgem is now at &aScratched" to victim
	if {Bliss.Astra.%victim%} is 6:
		send "&bYou lost &cenergy. &byour &5&lᴀsᴛʀᴀ &bgem is now at &bPristine" to victim