command /compostcircle <number> <player>: # number = Size of circle
    permission: op
    trigger:
        set {_pl} to location of arg-2        
        set {_step} to 1 # Set a larger step value here
        set {_iterations} to 360 * arg-1 / {_step}
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of happy villager at {_pl} ~ {_v} with extra 0 with force



command /speedcircle <number> <player>: # number = Size of circle
    permission: op
    trigger:
        set {_pl} to location of arg-2        
        set {_step} to 1 # Set a larger step value here
        set {_iterations} to 360 * arg-1 / {_step}
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(yellow, yellow, 1) at {_pl} ~ {_v} with extra 0
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force
            draw 1 of happy villager at {_pl} ~ {_v} with extra 0 with force


            
command /speedcirclelast <number> <player>: # number = Size of circle
    permission: op
    trigger:
        set {_pl} to location of arg-2
        set {_step} to 1 # Set a larger step value here
        set {_iterations} to 360 * arg-1 / {_step}

        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(yellow, yellow, 1) at {_pl} ~ {_v} with extra 0
            
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(yellow, yellow, 1) at {_pl} ~ {_v} with extra 0
            
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(yellow, yellow, 1) at {_pl} ~ {_v} with extra 0
            
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force
          
        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(yellow, yellow, 1) at {_pl} ~ {_v} with extra 0
            
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(yellow, yellow, 1) at {_pl} ~ {_v} with extra 0
            
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(yellow, yellow, 1) at {_pl} ~ {_v} with extra 0
            
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

        wait 0.4 second
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(yellow, yellow, 1) at {_pl} ~ {_v} with extra 0
            
            draw 1 of smoke at {_pl} ~ {_v} with extra 0 with force

