#speed powers
every 1 tick:
	loop all players:
		set {_uuid} to uuid of loop-player
		
		if loop-player's off hand item or loop-player's held item is a amethyst shard named "&e&lSpeed &f&lgem":
			send action bar "&e🔺%{Speed.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player


		if loop-player's off hand item is prismarine shard named "&e&lSpeed &f&lgem":

			send action bar "%{Speed.Power3.SpeedStorm.Display.%{_uuid}%}% &e🔮%{Speed.Power2.Enchanting.Display.%{_uuid}%}% &f%{Speed.Power1.SlothSedative.Display.%{_uuid}%}%" to loop-player
		
		if loop-player's held item or loop-player's held item is a amethyst shard named "&e&lSpeed &f&lgem":
			send action bar "&e🔺%{Speed.Power2.Enchanting.Display.%{_uuid}%}%" to loop-player



		if loop-player's held item is prismarine shard named "&e&lSpeed &f&lgem":
			send action bar "%{Speed.Power3.SpeedStorm.Display.%{_uuid}%}% &e🔮%{Speed.Power2.Enchanting.Display.%{_uuid}%}% &f%{Speed.Power1.SlothSedative.Display.%{_uuid}%}%" to loop-player

every 1 second:

	loop all players:

		if loop-player's off hand item is a amethyst shard named "&e&lSpeed &f&lgem":
			apply potion of speed of tier 1 to loop-player for 1.03 second


		if loop-player's off hand item is prismarine shard named "&e&lSpeed &f&lgem":
			apply potion of speed of tier 2 to loop-player for 1.03 second
		
		if loop-player's held item is a amethyst shard named "&e&lSpeed &f&lgem":
			apply potion of speed of tier 1 to loop-player for 1.03 second



		if loop-player's held item is prismarine shard named "&e&lSpeed &f&lgem":
			apply potion of speed of tier 2 to loop-player for 1.03 second




every 1 second:
	loop all players:
		if loop-player has a prismarine shard or amethyst shard named "&e&lSpeed &f&lgem":
			set {_uuid} to uuid of loop-player
			#SpeedStorm
			
			if {Speed.Power3.SpeedStorm.Second.%{_uuid}%} is not set:
				set {Speed.Power3.SpeedStorm.Second.%{_uuid}%} to 0
				set {Speed.Power3.SpeedStorm.Minute.%{_uuid}%} to 0
				set {Speed.Power3.SpeedStorm.Cooldown.%{_uuid}%} to true

			if {Speed.Power3.SpeedStorm.Display.%{_uuid}%} is not set:
				set {Speed.Power3.SpeedStorm.Display.%{_uuid}%} to "🌩 &b%{Speed.Power3.SpeedStorm.Minute.%{_uuid}%}%m %{Speed.Power3.SpeedStorm.Second.%{_uuid}%}%s"
				
		
			if {Speed.Power3.SpeedStorm.Cooldown.%{_uuid}%} is true:
				if {Speed.Power3.SpeedStorm.Minute.%{_uuid}%} is 0:
					set {Speed.Power3.SpeedStorm.Display.%{_uuid}%} to "🌩 &b%{Speed.Power3.SpeedStorm.Second.%{_uuid}%}%s"

				else:
					set {Speed.Power3.SpeedStorm.Display.%{_uuid}%} to "🌩 &b%{Speed.Power3.SpeedStorm.Minute.%{_uuid}%}%m %{Speed.Power3.SpeedStorm.Second.%{_uuid}%}%s"

			if {Speed.Power3.SpeedStorm.Cooldown.%{_uuid}%} is true:
				remove 1 from {Speed.Power3.SpeedStorm.Second.%{_uuid}%}



			if {Speed.Power3.SpeedStorm.Second.%{_uuid}%} is -1:
				remove 1 from {Speed.Power3.SpeedStorm.Minute.%{_uuid}%}
				set {Speed.Power3.SpeedStorm.Second.%{_uuid}%} to 59
                
			if {Speed.Power3.SpeedStorm.Minute.%{_uuid}%} is -1:
				set {Speed.Power3.SpeedStorm.Cooldown.%{_uuid}%} to false
				set {Speed.Power3.SpeedStorm.Display.%{_uuid}%} to "🌩 &aReady!"


			#Enchanting

			if {Speed.Power2.Enchanting.Second.%{_uuid}%} is not set:
				set {Speed.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Speed.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} to true

			if {Speed.Power2.Enchanting.Minute.%{_uuid}%} is not set:
				set {Speed.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Speed.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} to true



			if {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} is not set:
				set {Speed.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Speed.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} to true	
				set {Speed.Power2.Enchanting.Display.%{_uuid}%} to " &b%{Speed.Power2.Enchanting.Minute.%{_uuid}%}%m %{Speed.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Speed.Power2.Enchanting.Display.%{_uuid}%} is not set:
				set {Speed.Power2.Enchanting.Second.%{_uuid}%} to 0
				set {Speed.Power2.Enchanting.Minute.%{_uuid}%} to 0
				set {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} to true	

			if {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				set {Speed.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Speed.Power2.Enchanting.Minute.%{_uuid}%}%m %{Speed.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Speed.Power2.Enchanting.Display.%{_uuid}%} is not set:
				set {Speed.Power2.Enchanting.Display.%{_uuid}%} to " &b %{Speed.Power2.Enchanting.Minute.%{_uuid}%}%m %{Speed.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				if {Speed.Power2.Enchanting.Minute.%{_uuid}%} is 0:
					set {Speed.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Speed.Power2.Enchanting.Second.%{_uuid}%}%s"

				else:
					set {Speed.Power2.Enchanting.Display.%{_uuid}%} to "&b %{Speed.Power2.Enchanting.Minute.%{_uuid}%}%m %{Speed.Power2.Enchanting.Second.%{_uuid}%}%s"

			if {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} is true:
				remove 1 from {Speed.Power2.Enchanting.Second.%{_uuid}%}


			
			if {Speed.Power2.Enchanting.Second.%{_uuid}%} is -1:
				remove 1 from {Speed.Power2.Enchanting.Minute.%{_uuid}%}
				set {Speed.Power2.Enchanting.Second.%{_uuid}%} to 59
                
			if {Speed.Power2.Enchanting.Minute.%{_uuid}%} is -1:
				set {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} to false
				set {Speed.Power2.Enchanting.Display.%{_uuid}%} to " &aReady!"



			#SlothSedative





			if {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} is true:
				remove 1 from {Speed.Power1.SlothSedative.Second.%{_uuid}%}


			
			if {Speed.Power1.SlothSedative.Second.%{_uuid}%} is -1:
				remove 1 from {Speed.Power1.SlothSedative.Minute.%{_uuid}%}
				set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 59


			if {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} is true:
				if {Speed.Power1.SlothSedative.Minute.%{_uuid}%} is 0:
					set {Speed.Power1.SlothSedative.Display.%{_uuid}%} to "🎯 &b%{Speed.Power1.SlothSedative.Second.%{_uuid}%}%s"

				else:
					set {Speed.Power1.SlothSedative.Display.%{_uuid}%} to "🎯 &b%{Speed.Power1.SlothSedative.Minute.%{_uuid}%}%m %{Speed.Power1.SlothSedative.Second.%{_uuid}%}%s"


			if {Speed.Power1.SlothSedative.Second.%{_uuid}%} is not set:
				set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 0
				set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 0

			if {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} is not set:
				set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 0
				set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 0
				set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to true	
				set {Speed.Power1.SlothSedative.Display.%{_uuid}%} to "🎯 &b%{Speed.Power1.SlothSedative.Minute.%{_uuid}%}%m %{Speed.Power1.SlothSedative.Second.%{_uuid}%}%s"

			if {Speed.Power1.SlothSedative.Display.%{_uuid}%} is not set:
				set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 0
				set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 0
				set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to true	

			if {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} is true:
				set {Speed.Power1.SlothSedative.Display.%{_uuid}%} to "🎯 &b%{Speed.Power1.SlothSedative.Minute.%{_uuid}%}%m %{Speed.Power1.SlothSedative.Second.%{_uuid}%}%s"

			if {Speed.Power1.SlothSedative.Display.%{_uuid}%} is not set:
				set {Speed.Power1.SlothSedative.Display.%{_uuid}%} to "🎯 &b%{Speed.Power1.SlothSedative.Minute.%{_uuid}%}%m %{Speed.Power1.SlothSedative.Second.%{_uuid}%}%s"

                
			if {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} is true:
				set {Speed.Power1.SlothSedative.Display.%{_uuid}%} to "🎯 &b%{Speed.Power1.SlothSedative.Minute.%{_uuid}%}%m %{Speed.Power1.SlothSedative.Second.%{_uuid}%}%s"



			if {Speed.Power1.SlothSedative.Minute.%{_uuid}%} is -1:
				set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to false
				set {Speed.Power1.SlothSedative.Display.%{_uuid}%} to "🎯 &aReady!"


on sneak toggle:
	if {Tag..%player%} is 0:
		if player's off hand item is a amethyst shard named "&e&lSpeed &f&lgem":
			set {_uuid} to uuid of player
			if {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} is false:
				execute console command "enchant %player% efficiency 2"
				send "&aEnchanting Tool with &eefficiency &42"
				set {Speed.Power2.Enchanting.Second.%{_uuid}%} to 59
				set {Speed.Power2.Enchanting.Minute.%{_uuid}%} to 1
				set {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} to true
		if player's off hand item is a prismarine shard named "&e&lSpeed &f&lgem":
			set {_uuid} to uuid of player
			if {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} is false:
				execute console command "enchant %player% efficiency 5"
				send "&aEnchanting Tool with &eefficiency &45"
				set {Speed.Power2.Enchanting.Second.%{_uuid}%} to 59
				set {Speed.Power2.Enchanting.Minute.%{_uuid}%} to 1
				set {Speed.Power2.Enchanting.Cooldown.%{_uuid}%} to true	

on damage:
	if {Tag..%attacker%} is 0:
		if attacker's held item is a prismarine shard named "&e&lSpeed &f&lgem":
			if victim is a player:
				set {_uuid} to uuid of attacker
				if {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} is not true:
					send "you used &eSloth's Sedative" to attacker
					execute console command "effect give %victim% mining_fatigue 20 1"
					execute console command "effect give %victim% slowness 20 1"
					if {Bliss.Speed.%attacker%} > 4:
						set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 3
						set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 59
						set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to true
					if {Bliss.Speed.%attacker%} is 3:
						set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 5
						set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 59
						set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to true
					if {Bliss.Speed.%attacker%} < 3:
						set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 7
						set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 59
						set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to true
on left click:
	if {Tag..%player%} is 0:
		if player's held item is a prismarine shard named "&e&lSpeed &f&lgem":
			set {_uuid} to uuid of player
			if {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} is not true:
				send "you used &eSloth's Sedative &bGroup" to player
				execute console command "execute as %player% at @s run effect give @e[distance=1..7] mining_fatigue 20 1"
				execute console command "execute as %player% at @s run effect give @e[distance=1..7] slowness 20 1"
				if {Bliss.Speed.%player%} > 4:
					set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 3
					set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 59
					set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to true
				if {Bliss.Speed.%player%} is 3:
					set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 5
					set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 59
					set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to true
				if {Bliss.Speed.%player%} < 3:
					set {Speed.Power1.SlothSedative.Minute.%{_uuid}%} to 7
					set {Speed.Power1.SlothSedative.Second.%{_uuid}%} to 59
					set {Speed.Power1.SlothSedative.Cooldown.%{_uuid}%} to true


on drop prismarine shard:
	if event-item is prismarine shard named "&e&lSpeed &f&lgem":
		cancel event
on drop amethyst shard:
	if event-item is amethyst shard named "&e&lSpeed &f&lgem":
		cancel event
	
every 10 tick:
	loop all players:
		execute console command "execute as @e[type=armor_stand,tag=2] at @s run tp @a[tag=pp,distance=0.5..2.5] ~ ~ ~"
		execute console command "execute as @e[tag=2] at @s run fill ~6 ~3 ~6 ~-6 ~-4 ~-6 air replace fire"
		execute console command "execute as @e[tag=6] at @s run fill ~6 ~3 ~6 ~-6 ~-4 ~-6 air replace fire"
	
every 1 second:
	loop all players:
		execute console command "execute as @e[tag=6] at @s run execute as @e[distance=1..9,limit=1] at @s run summon lightning_bolt ~ ~2 ~"
		execute console command "execute as @e[tag=6] at @s run effect give @a[tag=69,distance=0..9] instant_health 1 0 true"
		execute console command "execute as @e[tag=6] at @s run effect give @a[tag=69,distance=0..9] speed 8 5 true"
		execute console command "execute as @e[tag=6] at @s run effect give @a[tag=69,distance=0..9] haste 8 9 true"
		execute console command "execute as @e[tag=6] at @s run particle minecraft:campfire_cosy_smoke ~ ~8 ~ 3 0 3 0 590 force @a"
		execute console command "execute as @e[tag=2] at @s run fill ~6 ~3 ~6 ~-6 ~-4 ~-6 air replace fire"
		execute console command "execute as @e[tag=6] at @s run fill ~6 ~3 ~6 ~-6 ~-4 ~-6 air replace fire"

on right click:
	if {Tag..%player%} is 0:
		if player's held item is a prismarine shard named "&e&lSpeed &f&lgem":
			set {_uuid} to uuid of player
			if {Tier2.Stregnth.%player%} is true:
				if {Speed.Power3.SpeedStorm.Cooldown.%{_uuid}%} is not true: 
					send "&e🌧 &aYou activated &eSpeed Storm"
					apply speed 6 to player for 4 seconds
					execute console command "tag %player% add 69"
					execute console command "execute as %player% at @s run execute as @a[distance=1.5..9] at @s run summon armor_stand ~ ~ ~ {Tags:[""2""],Invisible:1b}"
					execute console command "execute as %player% at @s run summon armor_stand ~ ~ ~ {Tags:[""6""],Invisible:1b}"
					execute console command "execute as %player% at @s run tag @a[distance=1..9] add pp"
					execute player command "/speedcircle 0.5"
					execute player command "/speedcircle 1"
					execute player command "/speedcircle 1.5"
					execute player command "/speedcircle 2"
					execute player command "/speedcircle 2.5"
					execute player command "/speedcircle 3"
					execute player command "/speedcircle 3.5"
					if {Bliss.Speed.%player%} > 4:
						set {Speed.Power3.SpeedStorm.Minute.%{_uuid}%} to 2
						set {Speed.Power3.SpeedStorm.Second.%{_uuid}%} to 35
						set {Speed.Power3.SpeedStorm.Cooldown.%{_uuid}%} to true
					if {Bliss.Speed.%player%} is 3:
						set {Speed.Power3.SpeedStorm.Minute.%{_uuid}%} to 3
						set {Speed.Power3.SpeedStorm.Second.%{_uuid}%} to 15
						set {Speed.Power3.SpeedStorm.Cooldown.%{_uuid}%} to true
					if {Bliss.Speed.%player%} < 3:
						set {Speed.Power3.SpeedStorm.Minute.%{_uuid}%} to 3
						set {Speed.Power3.SpeedStorm.Second.%{_uuid}%} to 45
						set {Speed.Power3.SpeedStorm.Cooldown.%{_uuid}%} to true

					set {Speed.Power3.SpeedStorm.Minute.%{_uuid}%} to 3
					set {Speed.Power3.SpeedStorm.Second.%{_uuid}%} to 15
					set {Speed.Power3.SpeedStorm.Cooldown.%{_uuid}%} to true
					execute console command "execute as @e[tag=6] at @s run function particles:speed"
					wait 15 seconds
					execute console command "kill @e[tag=6]"
					execute console command "kill @e[tag=2]"
					execute console command "tag %player% remove 69"
					execute console command "tag @a remove pp"
