on respawn:
	if {Bliss.Speed.%player%} is 1:
		give player a amethyst shard with custom model data 95 named "&e&lSpeed &f&lgem" with lore "&8Broken Gem", "&aAuto enchant's axe and pickaxe with efficiency 2/5", ".", "&eSpeed Storm Speed 2/3/4" and "&e&lApply Slowness 2 to your victim and lower their attack speed" 
	if {Bliss.Speed.%player%} is 2:
		give player a amethyst shard with custom model data 87 named "&e&lSpeed &f&lgem" with lore "&cRuined Gem", "&aAuto enchant's axe and pickaxe with efficiency 2/5", ".", "&eSpeed Storm Speed 2/3/4" and "&e&lApply Slowness 2 to your victim and lower their attack speed" 
	if {Bliss.Speed.%player%} is 3:
		give player a amethyst shard with custom model data 67 named "&e&lSpeed &f&lgem" with lore "&eDamaged Gem", "&aAuto enchant's axe and pickaxe with efficiency 2/5", ".", "&eSpeed Storm Speed 2/3/4" and "&e&lApply Slowness 2 to your victim and lower their attack speed" 
	if {Bliss.Speed.%player%} is 4:
		give player a amethyst shard with custom model data 47 named "&e&lSpeed &f&lgem" with lore "&aCracked Gem", "&aAuto enchant's axe and pickaxe with efficiency 2/5", ".", "&eSpeed Storm Speed 2/3/4" and "&e&lApply Slowness 2 to your victim and lower their attack speed" 
	if {Bliss.Speed.%player%} is 5:
		give player a amethyst shard with custom model data 27 named "&e&lSpeed &f&lgem" with lore "&aScratched Gem", "&aAuto enchant's axe and pickaxe with efficiency 2/5", ".", "&eSpeed Storm Speed 2/3/4" and "&e&lApply Slowness 2 to your victim and lower their attack speed" 
	if {Bliss.Speed.%player%} is 6:
		give player a amethyst shard with custom model data 7 named "&e&lSpeed &f&lgem" with lore "&bPristine Gem", "&aAuto enchant's axe and pickaxe with efficiency 2/5", ".", "&eSpeed Storm Speed 2/3/4" and "&e&lApply Slowness 2 to your victim and lower their attack speed" 
	if {Bliss.Speed.%player%} is 7:
		give player a amethyst shard with custom model data 7 named "&e&lSpeed &f&lgem" with lore "&bPristine + Gem", "&aAuto enchant's axe and pickaxe with efficiency 2/5", ".", "&eSpeed Storm Speed 2/3/4" and "&e&lApply Slowness 2 to your victim and lower their attack speed" 
	if {Bliss.Speed.%player%} is 8:
		give player a amethyst shard with custom model data 7 named "&e&lSpeed &f&lgem" with lore "&bPristine + 2 Gem", "&aAuto enchant's axe and pickaxe with efficiency 2/5", ".", "&eSpeed Storm Speed 2/3/4" and "&e&lApply Slowness 2 to your victim and lower their attack speed" 
	if {Bliss.Speed.%player%} is 9:
		give player a amethyst shard with custom model data 7 named "&e&lSpeed &f&lgem" with lore "&bPristine + 3 Gem", "&aAuto enchant's axe and pickaxe with efficiency 2/5", ".", "&eSpeed Storm Speed 2/3/4" and "&e&lApply Slowness 2 to your victim and lower their attack speed" 
	if {Bliss.Speed.%player%} is 10:
		give player a amethyst shard with custom model data 7 named "&e&lSpeed &f&lgem" with lore "&bPristine + 4 Gem", "&aAuto enchant's axe and pickaxe with efficiency 2/5", ".", "&eSpeed Storm Speed 2/3/4" and "&e&lApply Slowness 2 to your victim and lower their attack speed" 
	if {Bliss.Speed.%player%} > 10:
		set {item} to amethyst shard with custom model data 7 named "&e&lSpeed &f&lgem" with lore "&bPristine + 5 Gem", "&aAuto enchant's axe and pickaxe with efficiency 2/5", ".", "&eSpeed Storm Speed 2/3/4" and "&e&lApply Slowness 2 to your victim and lower their attack speed" 
		give player {item}
		enchant {item} with mending 1