command /lifecircle <number> <player>: # number = Size of circle
    permission: op
    trigger:
        set {_pl} to location of arg-2
        set {_step} to 4 # Set a larger step value here
        set {_iterations} to 360 * arg-1 / {_step}
        loop {_iterations} times:
            set {_angle} to loop-value * {_step}
            set {_v} to spherical vector radius arg-1, yaw {_angle}, pitch (0) # Pitch is set to 0 to make it around the player
            draw 1 of dust_color_transition using dustTransition(rgb(245, 0, 141), rgb(245, 0, 141), 1) at {_pl} ~ {_v} with extra 0.000000001




        
