on respawn:
	if {Bliss.Life.%player%} is 1:
		give player amethyst shard with custom model data 95 named "&d&lLife &lgem" with lore "&4Broken Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
	if {Bliss.Life.%player%} is 2:
		give player amethyst shard with custom model data 83 named "&d&lLife &lgem" with lore "&cRuined Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
	if {Bliss.Life.%player%} is 3:
		give player amethyst shard with custom model data 63 named "&d&lLife &lgem" with lore "&eDamaged Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
	if {Bliss.Life.%player%} is 4:
		give player amethyst shard with custom model data 43 named "&d&lLife &lgem" with lore "&aCracked Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
	if {Bliss.Life.%player%} is 5:
		give player amethyst shard with custom model data 23 named "&d&lLife &lgem" with lore "&aScratched Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
	if {Bliss.Life.%player%} is 6:
		give player amethyst shard with custom model data 3 named "&d&lLife &lgem" with lore "&bPristine Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
	if {Bliss.Life.%player%} is 7:
		give player amethyst shard with custom model data 3 named "&d&lLife &lgem" with lore "&bPristine + Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
	if {Bliss.Life.%player%} is 8:
		give player amethyst shard with custom model data 3 named "&d&lLife &lgem" with lore "&bPristine + 2 Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
	if {Bliss.Life.%player%} is 9:
		give player amethyst shard with custom model data 3 named "&d&lLife &lgem" with lore "&bPristine + 3 Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
	if {Bliss.Life.%player%} is 10:
		give player amethyst shard with custom model data 3 named "&d&lLife &lgem" with lore "&bPristine + 4 Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
	if {Bliss.Life.%player%} > 10:
		set {item} to amethyst shard with custom model data 3 named "&d&lLife &lgem" with lore "&bPristine + 5 Gem", "&aRegen To Trusted players 20s cooldown", "<red>" and "&dPasive regen" and "&dLower player's &amax health between 80%% and 5%%" 
		give player {item}
		enchant {item} with mending 1